# Builds one document A for the split verb from several files of the old method, in the order
# given, each file's text verbatim, separated by one blank line. The split verb takes one
# document and a run splits once (agent-runner skill), so a method whose rules sit in several
# files (a skill folder, a lifecycle page, a format README) is concatenated here first; the
# manifest's source hash then pins the bytes. Headings are not units, so the file boundaries
# change no unit; the first file keeps its frontmatter at the top of the document.
#
# Beside the document it writes <document>.files.md: order, file, characters and the line range
# each file occupies in the document, so run.md need not record the list by hand. The unit
# range per file needs the manifest, which exists only after the split: document-a-ranges.ps1
# joins the two afterwards and adds the units column.
#
#   .\make-document-a.ps1 -Root ..\.. -Files .claude/skills/v3-buildout/SKILL.md,...,fanout/PROTOCOL.md `
#       -Out .\2026-09-05-v3-buildout-2\document-a.md
#
# ASCII only: Windows PowerShell 5.1 reads an unmarked file as ANSI.
param(
    [Parameter(Mandatory)] [string] $Root,
    [Parameter(Mandatory)] [string[]] $Files,
    [Parameter(Mandatory)] [string] $Out
)

# .NET's file API resolves against the process directory, not PowerShell's location, so every
# path is made absolute here first; a missing file stops the script before anything is written.
$ErrorActionPreference = 'Stop'
$folder = [IO.Path]::GetFullPath((Join-Path (Get-Location) $Root))

$first = [IO.File]::ReadAllText((Join-Path $folder $Files[0]), [Text.Encoding]::UTF8)
$sep = if ($first.Contains("`r`n")) { "`r`n" } else { "`n" }

$pieces = @()
$rows = @()
$line = 1
$order = 0
foreach ($f in $Files) {
    $path = Join-Path $folder $f
    if (-not (Test-Path $path)) { throw "no such file: $path" }
    $text = [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8)
    $nl = if ($text.Contains("`r`n")) { "`r`n" } else { "`n" }
    $piece = $text.TrimEnd("`r", "`n") + $nl
    $pieces += $piece
    $count = ([regex]::Matches($piece, [regex]::Escape($nl))).Count
    $order++
    $rows += [pscustomobject]@{ Order = $order; File = $f; Characters = $text.Length; FirstLine = $line; LastLine = $line + $count - 1 }
    $line += $count + 1   # the separator is one blank line
    Write-Host ("{0,-24} {1,6} chars  lines {2}-{3}" -f $f, $text.Length, $rows[-1].FirstLine, $rows[-1].LastLine)
}

$doc = [string]::Join($sep, $pieces)

$target = [IO.Path]::GetFullPath((Join-Path (Get-Location) $Out))
[IO.File]::WriteAllText($target, $doc, (New-Object System.Text.UTF8Encoding($false)))
$sha = (Get-FileHash $target -Algorithm SHA256).Hash.ToLowerInvariant()

$filesMd = [IO.Path]::ChangeExtension($target, '.files.md')
$table = New-Object System.Collections.Generic.List[string]
$table.Add("# Files of $([IO.Path]::GetFileName($target)) - generated by ../make-document-a.ps1 on $(Get-Date -Format 'yyyy-MM-dd')")
$table.Add('')
$table.Add("Document sha256 $sha; $($rows.Count) files, $($doc.Length) chars. Line ranges are in the document; the units column is added by document-a-ranges.ps1 after the split.")
$table.Add('')
$table.Add('| order | file | characters | lines |')
$table.Add('|---|---|---|---|')
foreach ($r in $rows) { $table.Add("| $($r.Order) | $($r.File) | $($r.Characters) | $($r.FirstLine)-$($r.LastLine) |") }
[IO.File]::WriteAllText($filesMd, (($table -join "`n") + "`n"), (New-Object System.Text.UTF8Encoding($false)))

Write-Host "$($Files.Count) files -> $target ($($doc.Length) chars, sha256 $sha)"
Write-Host "file list -> $filesMd"
