namespace StoryPlanner.AgentRunner;

/// <summary>
/// Reads runs from disk: every <c>ledger.jsonl</c> under the fanout root is a run, its id the
/// path relative to that root. Builds the same <see cref="RunSnapshot"/> the host builds for
/// a live batch, so history and live are one view. A run whose <c>jobs.json</c> no longer
/// parses, or whose inputs have moved, is still listed from its ledger and marked so.
/// </summary>
public static class RunCatalog
{
    public static string RunIdFor(string runDir, string fanoutRoot) =>
        Path.GetRelativePath(fanoutRoot, runDir).Replace('\\', '/').TrimEnd('/');

    public static IEnumerable<string> RunDirs(string fanoutRoot)
    {
        if (!Directory.Exists(fanoutRoot)) yield break;
        foreach (var ledger in Directory.EnumerateFiles(fanoutRoot, "ledger.jsonl", SearchOption.AllDirectories))
            yield return Path.GetDirectoryName(ledger)!;
    }

    public static RunSnapshot Load(string runDir, string fanoutRoot) => Build(runDir, fanoutRoot, live: null);

    /// <summary>The one builder: disk first, then the live batch's harness state and in-flight set layered on.</summary>
    public static RunSnapshot Build(string runDir, string fanoutRoot, BatchRunner? live)
    {
        var runId = RunIdFor(runDir, fanoutRoot);
        var jobFilePath = Path.Combine(runDir, "jobs.json");
        var ledger = live?.LedgerSnapshot()
            ?? (File.Exists(Path.Combine(runDir, "ledger.jsonl")) ? RunnerPlan.ParseLedger(File.ReadLines(Path.Combine(runDir, "ledger.jsonl"))) : []);

        IReadOnlyList<ResolvedJob>? jobs = live?.Jobs;
        JobFile? jobFile = live?.JobFile;
        string? error = null;
        if (jobs is null && File.Exists(jobFilePath))
        {
            try
            {
                jobFile = RunnerPlan.ParseJobFile(File.ReadAllText(jobFilePath));
                jobs = RunnerPlan.Resolve(jobFile, runDir);
            }
            catch (Exception ex) when (ex is System.Text.Json.JsonException or InvalidOperationException)
            {
                error = $"jobs.json unusable: {ex.Message}";
            }
        }

        var inputsResolvable = jobs is not null && jobs.All(j => j.ProtocolFiles.Concat(j.InputFiles).All(File.Exists));
        var running = live?.RunningSnapshot().ToDictionary(r => r.JobId) ?? new Dictionary<string, RunningAttempt>();
        var maxAttempts = jobFile?.MaxAttempts ?? 1;

        var jobSnapshots = new List<JobSnapshot>();
        var ids = jobs?.Select(j => j.Id).ToList() ?? ledger.Select(r => r.JobId).Distinct().ToList();
        foreach (var id in ids)
        {
            var job = jobs?.FirstOrDefault(j => j.Id == id);
            var rows = ledger.Where(r => r.JobId == id).OrderBy(r => r.Attempt).ToList();
            var last = rows.LastOrDefault();
            var state = running.ContainsKey(id) ? "Running"
                : job is not null ? RunnerPlan.StateOf(job, ledger, maxAttempts).ToString()
                : rows.Any(r => r.Succeeded) ? "Succeeded" : rows.Count > 0 ? "Failed" : "Pending";
            double? seconds = null;
            string? startUtc = last?.StartUtc, endUtc = last?.EndUtc, streamPath = last?.ResultPath;
            if (running.TryGetValue(id, out var ra))
            {
                startUtc = ra.StartUtc.ToString("o"); endUtc = null; streamPath = ra.StreamPath;
                seconds = (DateTimeOffset.UtcNow - ra.StartUtc).TotalSeconds;
            }
            else if (last is not null && DateTimeOffset.TryParse(last.StartUtc, out var s) && DateTimeOffset.TryParse(last.EndUtc, out var e))
                seconds = (e - s).TotalSeconds;
            jobSnapshots.Add(new JobSnapshot(id, job?.Item ?? "(job file not readable)", job?.Model ?? last?.Model ?? "?", state,
                rows.Count, last?.ExitCode, last?.OutputCheck, rows.Sum(r => r.CostUsd ?? 0), startUtc, endUtc, seconds, streamPath));
        }

        var runMdPath = Path.Combine(runDir, "run.md");
        var stages = new RunStages(
            Instrument: HasInstrument(runDir, out var codebookDir),
            Calibrated: codebookDir is null ? null : Directory.EnumerateFiles(codebookDir, "calibration-*.md").Any(),
            Enumerated: File.Exists(Path.Combine(runDir, "items", "manifest.md")),
            Generated: File.Exists(jobFilePath) && File.ReadAllText(jobFilePath).Contains("Generated by", StringComparison.Ordinal),
            Piloted: ledger.Any(r => r.Mode == "pilot"),
            BatchComplete: jobSnapshots.Count > 0 && jobSnapshots.All(j => j.State is "Succeeded" or "Failed"),
            Tallied: HasFile(runDir, "tally.*") || HasFile(Path.GetDirectoryName(runDir)!, "tally.*"),
            Documented: File.Exists(runMdPath));

        var work = runId.Contains('/') ? runId[..runId.IndexOf('/')] : runId;
        var lastActivity = ledger.Select(r => r.EndUtc).Where(s => !string.IsNullOrEmpty(s)).OrderBy(s => s).LastOrDefault();

        return new RunSnapshot(
            runId, runDir, work,
            Live: live is not null && !live.Completed,
            Completed: live?.Completed ?? jobSnapshots.All(j => j.State is "Succeeded" or "Failed"),
            Paused: live?.Paused ?? false,
            StopRequested: live?.StopRequested ?? false,
            MaxParallel: live?.MaxParallel ?? jobFile?.MaxParallel,
            InFlight: running.Count,
            HoldReason: live?.HoldReason(),
            Jobs: jobSnapshots,
            Pending: jobSnapshots.Count(j => j.State == "Pending"),
            Succeeded: jobSnapshots.Count(j => j.State == "Succeeded"),
            Failed: jobSnapshots.Count(j => j.State == "Failed"),
            CostUsd: ledger.Sum(r => r.CostUsd ?? 0),
            InputsResolvable: inputsResolvable,
            Error: error,
            RunMd: File.Exists(runMdPath) ? File.ReadAllText(runMdPath) : null,
            Stages: stages,
            LastActivityUtc: lastActivity,
            NotBeforeUtc: live?.NotBefore?.ToString("o"),
            Scheduled: live is { Started: false, NotBefore: not null });
    }

    private static bool HasInstrument(string runDir, out string? codebookDir)
    {
        codebookDir = null;
        foreach (var dir in new[] { runDir, Path.GetDirectoryName(runDir)! })
        {
            if (File.Exists(Path.Combine(dir, "codebook.md"))) { codebookDir = dir; return true; }
            if (File.Exists(Path.Combine(dir, "protocol.md"))) return true;
        }
        return false;
    }

    private static bool HasFile(string dir, string pattern) =>
        Directory.Exists(dir) && Directory.EnumerateFiles(dir, pattern).Any();
}
