// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoryPlanner;
using StoryPlanner.Core;

#nullable disable

namespace StoryPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212033942_DescriptionFields")]
    partial class DescriptionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("StoryPlanner.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("StoryPlanner.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inspiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StoryPlanner.Models.CodexEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodexEntries");
                });

            modelBuilder.Entity("StoryPlanner.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("StoryPlanner.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodexEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStrictRule")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoryThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CodexEntryId");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("StoryThreadId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Models.NoteDependency", b =>
                {
                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PrerequisiteId", "DependentId");

                    b.HasIndex("DependentId");

                    b.ToTable("NoteDependency");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Intensity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerbatimText")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorldDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("LocationId");

                    b.ToTable("PlotPoints");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointCharacter", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevelopmentImpact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevelopmentNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("PlotPointCharacter");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointDependency", b =>
                {
                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrerequisiteId", "DependentId");

                    b.HasIndex("DependentId");

                    b.ToTable("PlotPointDependency");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointNote", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "NoteId");

                    b.HasIndex("NoteId");

                    b.ToTable("PlotPointNotes");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointTheme", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prominence")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "ThemeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("PlotPointTheme");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointThread", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "ThreadId");

                    b.HasIndex("StoryThreadId");

                    b.ToTable("PlotPointThread");
                });

            modelBuilder.Entity("StoryPlanner.Models.SourceMaterial", b =>
                {
                    b.Property<int>("SourceMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SourceMaterialId");

                    b.ToTable("SourceMaterials");
                });

            modelBuilder.Entity("StoryPlanner.Models.StoryThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("StoryPlanner.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("StoryPlanner.Models.Note", b =>
                {
                    b.HasOne("StoryPlanner.Models.Chapter", "Chapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Models.Character", "Character")
                        .WithMany("Notes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Models.CodexEntry", "CodexEntry")
                        .WithMany("Notes")
                        .HasForeignKey("CodexEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Models.SourceMaterial", "SourceMaterial")
                        .WithMany("Notes")
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StoryPlanner.Models.StoryThread", "StoryThread")
                        .WithMany("Notes")
                        .HasForeignKey("StoryThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Models.Theme", "Theme")
                        .WithMany("Notes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chapter");

                    b.Navigation("Character");

                    b.Navigation("CodexEntry");

                    b.Navigation("SourceMaterial");

                    b.Navigation("StoryThread");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("StoryPlanner.Models.NoteDependency", b =>
                {
                    b.HasOne("StoryPlanner.Models.Note", "Dependent")
                        .WithMany("Prerequisites")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Models.Note", "Prerequisite")
                        .WithMany("Dependents")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dependent");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPoint", b =>
                {
                    b.HasOne("StoryPlanner.Models.Chapter", "Chapter")
                        .WithMany("PlotPoints")
                        .HasForeignKey("ChapterId");

                    b.HasOne("StoryPlanner.Models.Location", "Location")
                        .WithMany("PlotPoints")
                        .HasForeignKey("LocationId");

                    b.Navigation("Chapter");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointCharacter", b =>
                {
                    b.HasOne("StoryPlanner.Models.Character", "Character")
                        .WithMany("Appearances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Models.PlotPoint", "PlotPoint")
                        .WithMany("CharacterAppearances")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("PlotPoint");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointDependency", b =>
                {
                    b.HasOne("StoryPlanner.Models.PlotPoint", "Dependent")
                        .WithMany("Prerequisites")
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Models.PlotPoint", "Prerequisite")
                        .WithMany("Dependents")
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dependent");

                    b.Navigation("Prerequisite");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointNote", b =>
                {
                    b.HasOne("StoryPlanner.Models.Note", "Note")
                        .WithMany("PlotPointReferences")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Models.PlotPoint", "PlotPoint")
                        .WithMany("NoteReferences")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("PlotPoint");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointTheme", b =>
                {
                    b.HasOne("StoryPlanner.Models.PlotPoint", "PlotPoint")
                        .WithMany("ThemeAssignments")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Models.Theme", "Theme")
                        .WithMany("PlotPointAssignments")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlotPoint");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPointThread", b =>
                {
                    b.HasOne("StoryPlanner.Models.PlotPoint", "PlotPoint")
                        .WithMany("ThreadAssignments")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Models.StoryThread", "StoryThread")
                        .WithMany("PlotPointAssignments")
                        .HasForeignKey("StoryThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlotPoint");

                    b.Navigation("StoryThread");
                });

            modelBuilder.Entity("StoryPlanner.Models.Chapter", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPoints");
                });

            modelBuilder.Entity("StoryPlanner.Models.Character", b =>
                {
                    b.Navigation("Appearances");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Models.CodexEntry", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Models.Location", b =>
                {
                    b.Navigation("PlotPoints");
                });

            modelBuilder.Entity("StoryPlanner.Models.Note", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("PlotPointReferences");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("StoryPlanner.Models.PlotPoint", b =>
                {
                    b.Navigation("CharacterAppearances");

                    b.Navigation("Dependents");

                    b.Navigation("NoteReferences");

                    b.Navigation("Prerequisites");

                    b.Navigation("ThemeAssignments");

                    b.Navigation("ThreadAssignments");
                });

            modelBuilder.Entity("StoryPlanner.Models.SourceMaterial", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Models.StoryThread", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPointAssignments");
                });

            modelBuilder.Entity("StoryPlanner.Models.Theme", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPointAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
