// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoryPlanner.Core;

#nullable disable

namespace StoryPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101215207_IdeasAttempt2")]
    partial class IdeasAttempt2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("StoryPlanner.Core.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Inspiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.CodexEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CodexEntries");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.GeminiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeminiEntries");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CodexEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsFurtherAnalysis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoryThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CodexEntryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SourceMaterialId");

                    b.HasIndex("StoryThreadId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoreDriver")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInChapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Presentation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stakes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TensionPhase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerbatimText")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorldDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("LocationId");

                    b.ToTable("PlotPoints");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointCharacter", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DevelopmentImpact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevelopmentNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogicalOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("PlotPointCharacters");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointCodexEntry", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodexEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LogicalOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsageType")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "CodexEntryId");

                    b.HasIndex("CodexEntryId");

                    b.ToTable("PlotPointCodexEntries");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointTheme", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Commentary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prominence")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "ThemeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("PlotPointThemes");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointThread", b =>
                {
                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImpactDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadTrajectory")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlotPointId", "ThreadId");

                    b.HasIndex("StoryThreadId");

                    b.ToTable("PlotPointThreads");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.SourceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceMaterials");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.StoryThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadScope")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Note", b =>
                {
                    b.HasOne("StoryPlanner.Core.Models.Chapter", "Chapter")
                        .WithMany("Notes")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Core.Models.Character", "Character")
                        .WithMany("Notes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Core.Models.CodexEntry", "CodexEntry")
                        .WithMany("Notes")
                        .HasForeignKey("CodexEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Core.Models.Location", "Location")
                        .WithMany("Notes")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Core.Models.SourceMaterial", "SourceMaterial")
                        .WithMany("Notes")
                        .HasForeignKey("SourceMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StoryPlanner.Core.Models.StoryThread", "StoryThread")
                        .WithMany("Notes")
                        .HasForeignKey("StoryThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StoryPlanner.Core.Models.Theme", "Theme")
                        .WithMany("Notes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chapter");

                    b.Navigation("Character");

                    b.Navigation("CodexEntry");

                    b.Navigation("Location");

                    b.Navigation("SourceMaterial");

                    b.Navigation("StoryThread");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPoint", b =>
                {
                    b.HasOne("StoryPlanner.Core.Models.Chapter", "Chapter")
                        .WithMany("PlotPoints")
                        .HasForeignKey("ChapterId");

                    b.HasOne("StoryPlanner.Core.Models.Location", "Location")
                        .WithMany("PlotPoints")
                        .HasForeignKey("LocationId");

                    b.Navigation("Chapter");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointCharacter", b =>
                {
                    b.HasOne("StoryPlanner.Core.Models.Character", "Character")
                        .WithMany("Appearances")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Core.Models.PlotPoint", "PlotPoint")
                        .WithMany("CharacterAppearances")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("PlotPoint");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointCodexEntry", b =>
                {
                    b.HasOne("StoryPlanner.Core.Models.CodexEntry", "CodexEntry")
                        .WithMany("PlotPointReferences")
                        .HasForeignKey("CodexEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Core.Models.PlotPoint", "PlotPoint")
                        .WithMany("CodexReferences")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodexEntry");

                    b.Navigation("PlotPoint");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointTheme", b =>
                {
                    b.HasOne("StoryPlanner.Core.Models.PlotPoint", "PlotPoint")
                        .WithMany("ThemeAssignments")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Core.Models.Theme", "Theme")
                        .WithMany("PlotPointAssignments")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlotPoint");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPointThread", b =>
                {
                    b.HasOne("StoryPlanner.Core.Models.PlotPoint", "PlotPoint")
                        .WithMany("ThreadAssignments")
                        .HasForeignKey("PlotPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryPlanner.Core.Models.StoryThread", "StoryThread")
                        .WithMany("PlotPointAssignments")
                        .HasForeignKey("StoryThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlotPoint");

                    b.Navigation("StoryThread");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Chapter", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPoints");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Character", b =>
                {
                    b.Navigation("Appearances");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.CodexEntry", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPointReferences");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Location", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPoints");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.PlotPoint", b =>
                {
                    b.Navigation("CharacterAppearances");

                    b.Navigation("CodexReferences");

                    b.Navigation("ThemeAssignments");

                    b.Navigation("ThreadAssignments");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.SourceMaterial", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.StoryThread", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPointAssignments");
                });

            modelBuilder.Entity("StoryPlanner.Core.Models.Theme", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("PlotPointAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
