// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoryPlanner.Core;

#nullable disable

namespace StoryPlanner.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("StoryPlanner.Core.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chapters", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArcSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BlockCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConversationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFilePrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.ConversationBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDecisions")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompaction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConversationBlocks", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.ConversationSubjectCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConversationSubjectCoverages", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.ConversationSubjectCoverageTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConversationSubjectCoverageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NoteTrackDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConversationSubjectCoverageTracks", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.GeminiEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeminiEntries", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ideas", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.IgnoredConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IgnoredConversations", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.NarrativePropertyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NarrativePropertyDefinitions", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.NarrativePropertyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValueDefinitionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NarrativePropertyValues", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.NarrativePropertyValueDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NarrativePropertyDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NarrativePropertyValueDefinitions", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("NoteState")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoteTrackDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorldDateEndDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorldDateEndMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorldDateEndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorldDateStartDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorldDateStartMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorldDateStartYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.NoteTrackDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuditDirective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AuditModeDisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanEditInAuditMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpansionModeDisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GardenerModeDisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkingModeDisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnerType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SceneDesignModeDisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsSourceMaterial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTheme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsWorldDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsWorldDateEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsageDirective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NoteTrackDefinitions", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Pivot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pivots", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.PlotPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FabulaDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FabulaMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FabulaYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInChapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TheaterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlotPoints", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.PlotPointSubjectLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlotPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlotPointSubjectLinks", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.SourceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourceMaterials", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stories", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TheaterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Subjects", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.SubjectDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubjectDefinitions", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Theaters", (string)null);
                });

            modelBuilder.Entity("StoryPlanner.Core.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Proposition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Themes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
