using System.Text;

namespace StoryPlanner.DocIntegrity;

/// <summary>
/// Writes everything generated, and only as whole files. <c>map.md</c> is rewritten from the
/// tables on every call; <c>state.md</c> is the <c>state</c> verb's. Authored files are never
/// written, with one exception that exists to retire the earlier convention: a generated
/// block left inside an authored file (the <c>level-1</c> and <c>activity</c> sections of
/// 2026-09-05) is removed by the tool that wrote it, so that the only writer of generated
/// text is also its only remover. After the first render under this rule there are none.
///
/// Generated files are denied to sessions by path in the project settings and regenerated by
/// the write hook after every passing validate, so they are a function of the tables at every
/// moment: never hand-edited, never stale.
/// </summary>
public static class Render
{
    public const string MapFile = "map.md";

    /// <summary>Renders the folder. Returns the paths written, map.md always last.</summary>
    public static IReadOnlyList<string> Write(string skillFolder, SkillDocument doc, ValidationReport report, bool forced)
    {
        MermaidRenderer.CheckNodeIds(doc);
        var written = new List<string>();

        foreach (var path in AuthoredFiles(doc))
        {
            var text = File.ReadAllText(path);
            if (!HasGeneratedBlock(text)) continue;
            File.WriteAllText(path, StripGenerated(text));
            written.Add(path);
        }

        var mapPath = Path.Combine(skillFolder, MapFile);
        File.WriteAllText(mapPath, MermaidRenderer.Map(doc, report, forced));
        written.Add(mapPath);
        return written;
    }

    /// <summary>SKILL.md and every activity file that exists on disk.</summary>
    public static IEnumerable<string> AuthoredFiles(SkillDocument doc)
    {
        yield return doc.SkillPath;
        foreach (var a in doc.Activities)
        {
            var path = doc.ActivityPath(a.Id);
            if (File.Exists(path)) yield return path;
        }
    }

    public static bool HasGeneratedBlock(string markdown)
        => markdown.Replace("\r\n", "\n").Split('\n')
            .Any(l => l.Trim().StartsWith(MapTables.GeneratedOpenPrefix, StringComparison.Ordinal));

    /// <summary>
    /// Removes every marker-delimited generated block, markers included, leaving at most one
    /// blank line where it stood. Everything else is copied through byte for byte, in the
    /// file's own newline style.
    /// </summary>
    public static string StripGenerated(string markdown)
    {
        var newline = markdown.Contains("\r\n") ? "\r\n" : "\n";
        var lines = markdown.Replace("\r\n", "\n").Split('\n');
        var kept = new List<string>();

        for (var i = 0; i < lines.Length; i++)
        {
            var trimmed = lines[i].Trim();
            if (!trimmed.StartsWith(MapTables.GeneratedOpenPrefix, StringComparison.Ordinal))
            {
                kept.Add(lines[i]);
                continue;
            }

            var close = i + 1;
            while (close < lines.Length && lines[close].Trim() != MapTables.GeneratedClose) close++;
            if (close >= lines.Length)
                throw new MapFormatException(
                    $"line {i + 1}: a generated block is never closed by {MapTables.GeneratedClose}.");

            // Collapse the blank line that preceded the block and the one that follows it into one.
            if (kept.Count > 0 && kept[^1].Length == 0 && close + 1 < lines.Length && lines[close + 1].Length == 0)
                close++;
            i = close;
        }

        var text = string.Join(newline, kept);
        return text;
    }
}
