using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace StoryPlanner.DocIntegrity;

/// <summary>
/// Writes <c>state.md</c>: what is here, read from the study registry and the files on
/// disk, never what to do next. Three sections, ruled 2026-09-05:
///
/// - per study, the study-scoped artifacts present (paths from the Artifacts table,
///   placeholders as wildcards) and the furthest process in chain order whose study-scoped
///   writes all exist;
/// - per corpus, the open questions, each with the calibrated codebook versions whose
///   <c>## Questions</c> section names it and the rounds whose <c>round.md</c> answered it;
/// - per hypothesis, the frontmatter status as authored, the status its entries after the last
///   <c>iteration</c> line imply, and the open questions naming it.
///
/// Where the files a section needs are absent, the section says absent, never empty. Whether a
/// challenging entry is resolved is not derived: the record has no entry kind for it.
/// </summary>
public static class StateBuilder
{
    /// <summary>
    /// Chain membership by study type, from schemas/study-registry-schema.md. A closed set
    /// here because the registry names types, not chains; an activity a chain names that the
    /// tables do not carry is skipped and said so.
    /// </summary>
    static readonly string[] ExploratoryChain =
        ["preparing-to-explore-a-corpus", "exploring-a-corpus", "reviewing-leads"];

    static readonly string[] VerificationChain =
        ["preparing-to-verify-a-corpus", "conducting-a-verification-round", "writing-candidates-from-verification",
         "refereeing-a-candidate", "promoting-checked-candidates"];

    static readonly string[] RefereeChain = ["preparing-to-verify-a-corpus"];

    static readonly Regex RefereeStudy = new("^referee-[0-9]+$", RegexOptions.Compiled);
    static readonly Regex CalibrationTitle = new(@"^#\s*Calibration\s*—\s*(?<id>[^@\s]+)@(?<hash>[0-9a-f]{6,64})", RegexOptions.Compiled);
    static readonly Regex HypothesesLine = new(@"^-\s*hypotheses:\s*(?<ids>.*)$", RegexOptions.Compiled);

    public sealed record Study(string Id, string Type, string Corpus, string Go);

    public sealed record Question(string Corpus, string Title, string Status, IReadOnlyList<int> Hypotheses)
    {
        public bool IsOpen => Status.StartsWith("open", StringComparison.OrdinalIgnoreCase);
    }

    public sealed record CodebookVersion(string RelativePath, string Hash, IReadOnlyList<string> Questions, bool Calibrated)
    {
        /// <summary>Folder and version without the extension, at the short hash: the form an evidence entry cites.</summary>
        public string Cite => $"{RelativePath[..^Path.GetExtension(RelativePath).Length]}@{Hash[..6]}";
    }

    public sealed record Hypothesis(int Id, string Slug, string Status, string Baselined, string Implied);

    public static string Build(string repoRoot, SkillDocument doc, bool forced = false)
    {
        var sb = new StringBuilder();
        sb.Append("# state.md — generated by process-docs/StoryPlanner.DocIntegrity\n\n");
        sb.Append("Never hand-edited: `render` rewrites this file whole from the study registry, the question " +
                  "lists, the hypothesis files, the study folders and the codebooks on disk. What is here, " +
                  "never what to do next; the pick is Brian's.\n\n");
        if (forced)
            sb.Append("> **UNVALIDATED** — written with `--force` while `check` still fails. Not authoritative.\n\n");

        var questions = ReadQuestions(repoRoot, doc, out var questionsNote);
        Studies(sb, repoRoot, doc);
        Corpora(sb, repoRoot, doc, questions, questionsNote);
        Hypotheses(sb, repoRoot, doc, questions);
        return sb.ToString();
    }

    // ---- studies ----

    static void Studies(StringBuilder sb, string repoRoot, SkillDocument doc)
    {
        sb.Append("## Studies\n\n");
        var row = doc.Artifact(WellKnown.Studies);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var registryPath, out _))
        {
            sb.Append($"No `{WellKnown.Studies}` artifact row with a parseable path; the registry cannot be located.\n\n");
            return;
        }
        var registry = Path.Combine(repoRoot, registryPath!.Pattern.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(registry))
        {
            sb.Append($"Registry absent: `{registryPath.Pattern}` does not exist.\n\n");
            return;
        }

        var studies = ReadRegistry(registry);
        if (studies.Count == 0)
        {
            sb.Append($"Registry `{registryPath.Pattern}` holds no rows.\n\n");
            return;
        }

        foreach (var study in studies)
        {
            sb.Append($"### {study.Id}\n\n");
            sb.Append($"- type: {study.Type} · corpus: {study.Corpus} · go: {study.Go}\n");

            var chain = ChainFor(study);
            if (chain is null)
            {
                sb.Append($"- chain: unknown type '{study.Type}'; nothing derived\n\n");
                continue;
            }
            var missing = chain.Where(a => !doc.Activities.Any(x => x.Id == a)).ToList();
            var processes = chain.SelectMany(doc.ProcessesOf).ToList();
            var folder = StudyFolder(study.Id);

            var scoped = processes.SelectMany(p => p.Writes).Distinct(StringComparer.Ordinal)
                .Select(doc.Artifact).Where(a => a is not null).Select(a => a!)
                .Where(a => ArtifactPath.TryParse(a.Path, out var ap, out _) && ap!.IsStudyScoped)
                .ToList();

            var present = new Dictionary<string, int>(StringComparer.Ordinal);
            sb.Append("- artifacts present:");
            var any = false;
            foreach (var a in scoped)
            {
                ArtifactPath.TryParse(a.Path, out var ap, out _);
                var count = CountMatches(repoRoot, ap!, folder, study.Corpus);
                present[a.Id] = count;
                if (count == 0) continue;
                any = true;
                sb.Append($" {a.Id}");
                if (count > 1) sb.Append($" ({count})");
                if (a.Id == WellKnown.Candidates)
                    foreach (var file in Matches(repoRoot, ap!, folder, study.Corpus))
                        sb.Append($" [{CandidateCounts(file)}]");
            }
            sb.Append(any ? "\n" : " none\n");

            string? furthest = null;
            foreach (var p in processes)
            {
                var writes = p.Writes.Where(present.ContainsKey).ToList();
                if (writes.Count == 0) continue;
                if (writes.All(w => present[w] > 0)) furthest = $"{p.Id} ({p.Activity})";
            }
            sb.Append($"- furthest process whose study-scoped writes all exist: {furthest ?? "none"}\n");
            if (missing.Count > 0)
                sb.Append($"- chain activities the tables do not carry, skipped: {string.Join(" ", missing)}\n");
            sb.Append('\n');
        }
    }

    static IReadOnlyList<Study> ReadRegistry(string path)
    {
        var tables = MapTables.ReadAll(File.ReadAllText(path));
        var table = tables.FirstOrDefault(t =>
            t.Headers.Select(h => h.ToLowerInvariant()).SequenceEqual(["id", "type", "corpus", "go"]));
        if (table is null)
            throw new MapFormatException($"{Path.GetFileName(path)}: no table with columns id | type | corpus | go.");
        return table.Rows.Select(r => new Study(r.Cells[0], r.Cells[1], r.Cells[2], r.Cells[3])).ToList();
    }

    static string[]? ChainFor(Study study)
    {
        if (RefereeStudy.IsMatch(study.Id)) return RefereeChain;
        return study.Type switch
        {
            "exploratory" => ExploratoryChain,
            "verification" => VerificationChain,
            _ => null,
        };
    }

    /// <summary>The referee's folder is <c>fanout/referee/</c> for every <c>referee-&lt;n&gt;</c> (schemas/study-registry-schema.md).</summary>
    public static string StudyFolder(string studyId)
        => RefereeStudy.IsMatch(studyId) ? "referee" : studyId;

    static string CandidateCounts(string file)
    {
        var lines = File.ReadAllText(file).Replace("\r\n", "\n").Split('\n').Select(l => l.TrimEnd()).ToList();
        var candidates = lines.Count(l => l.StartsWith("## C-", StringComparison.Ordinal));
        var referee = lines.Count(l => l.TrimStart().StartsWith("- referee:", StringComparison.Ordinal));
        var outcome = lines.Count(l => l.TrimStart().StartsWith("- outcome:", StringComparison.Ordinal));
        return $"{candidates} candidate(s), {referee} referee line(s), {outcome} outcome line(s)";
    }

    // ---- files on disk matching an artifact's pattern ----

    public static IReadOnlyList<string> Matches(string repoRoot, ArtifactPath path, string? studyFolder, string? corpus)
    {
        if (path.OutsideRepo) return [];
        var prefix = path.FixedPrefix(studyFolder, corpus);
        var dir = prefix.Length == 0 ? repoRoot : Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar));
        if (!Directory.Exists(dir)) return [];

        var regex = path.ToRegex(studyFolder, corpus);
        var entries = path.IsDirectory
            ? Directory.GetDirectories(dir, "*", SearchOption.AllDirectories)
                .Where(d => Directory.EnumerateFiles(d, "*", SearchOption.AllDirectories).Any())
            : Directory.GetFiles(dir, "*", SearchOption.AllDirectories);

        return entries
            .Where(e => regex.IsMatch(Path.GetRelativePath(repoRoot, e).Replace('\\', '/')))
            .OrderBy(e => e, StringComparer.Ordinal)
            .ToList();
    }

    static int CountMatches(string repoRoot, ArtifactPath path, string? studyFolder, string? corpus)
        => Matches(repoRoot, path, studyFolder, corpus).Count;

    // ---- corpora ----

    static IReadOnlyList<Question> ReadQuestions(string repoRoot, SkillDocument doc, out string? note)
    {
        note = null;
        var row = doc.Artifact(WellKnown.QuestionList);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _))
        {
            note = $"No `{WellKnown.QuestionList}` artifact row with a parseable path; the lists cannot be located.";
            return [];
        }
        var prefix = path!.FixedPrefix();
        if (!Directory.Exists(Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar))))
        {
            note = $"Question lists absent: `{prefix}/` does not exist.";
            return [];
        }

        var questions = new List<Question>();
        foreach (var file in Matches(repoRoot, path, null, null))
        {
            var corpus = Path.GetFileNameWithoutExtension(file);
            questions.AddRange(ParseQuestions(corpus, File.ReadAllText(file)));
        }
        if (questions.Count == 0) note = $"Question lists under `{prefix}/` hold no entries.";
        return questions;
    }

    public static IReadOnlyList<Question> ParseQuestions(string corpus, string text)
    {
        var result = new List<Question>();
        string? title = null;
        var status = "";
        var hypotheses = new List<int>();

        void Flush()
        {
            if (title is not null) result.Add(new Question(corpus, title, status, hypotheses));
            title = null; status = ""; hypotheses = [];
        }

        foreach (var raw in text.Replace("\r\n", "\n").Split('\n'))
        {
            var line = raw.Trim();
            if (line.StartsWith("### ", StringComparison.Ordinal)) { Flush(); title = line[4..].Trim(); continue; }
            if (line.StartsWith("## ", StringComparison.Ordinal) || line.StartsWith("# ", StringComparison.Ordinal)) { Flush(); continue; }
            if (title is null) continue;
            if (line.StartsWith("- status:", StringComparison.Ordinal)) status = line["- status:".Length..].Trim();
            var m = HypothesesLine.Match(line);
            if (m.Success)
                foreach (var tok in m.Groups["ids"].Value.Split([',', ' '], StringSplitOptions.RemoveEmptyEntries))
                    if (int.TryParse(tok, out var id)) hypotheses.Add(id);
        }
        Flush();
        return result;
    }

    static void Corpora(StringBuilder sb, string repoRoot, SkillDocument doc, IReadOnlyList<Question> questions, string? note)
    {
        sb.Append("## Corpora\n\n");
        if (note is not null) { sb.Append(note).Append("\n\n"); if (questions.Count == 0) return; }

        var codebooks = ReadCodebooks(repoRoot, doc);
        var rounds = ReadRounds(repoRoot, doc);

        foreach (var corpus in questions.Select(q => q.Corpus).Distinct(StringComparer.Ordinal).OrderBy(c => c, StringComparer.Ordinal))
        {
            var mine = questions.Where(q => q.Corpus == corpus).ToList();
            var open = mine.Where(q => q.IsOpen).ToList();
            sb.Append($"### {corpus}\n\n");
            sb.Append($"{open.Count} open, {mine.Count - open.Count} withdrawn.\n\n");
            if (open.Count == 0) continue;
            sb.Append("| question | hypotheses | covered by (calibrated codebook) | answered by (round) |\n|---|---|---|---|\n");
            foreach (var q in open)
            {
                var covering = codebooks.Where(c => c.Calibrated && c.Questions.Contains(q.Title, StringComparer.Ordinal)).Select(c => c.Cite).ToList();
                var answering = rounds.Where(r => r.Questions.Contains(q.Title, StringComparer.Ordinal)).Select(r => r.Study).ToList();
                sb.Append("| ").Append(q.Title.Replace("|", "\\|"))
                  .Append(" | ").Append(q.Hypotheses.Count == 0 ? "—" : string.Join(" ", q.Hypotheses.Select(h => h.ToString("000"))))
                  .Append(" | ").Append(covering.Count == 0 ? "nothing" : string.Join(" ", covering))
                  .Append(" | ").Append(answering.Count == 0 ? "nothing" : string.Join(" ", answering))
                  .Append(" |\n");
            }
            sb.Append('\n');
        }
    }

    static IReadOnlyList<CodebookVersion> ReadCodebooks(string repoRoot, SkillDocument doc)
    {
        var row = doc.Artifact(WellKnown.Codebook);
        var calRow = doc.Artifact(WellKnown.Calibration);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _)) return [];

        var accepted = new HashSet<string>(StringComparer.Ordinal); // hash prefixes with an accepting calibration
        if (calRow is not null && ArtifactPath.TryParse(calRow.Path, out var calPath, out _))
            foreach (var file in Matches(repoRoot, calPath!, null, null))
            {
                var text = File.ReadAllText(file).Replace("\r\n", "\n");
                var first = text.Split('\n').FirstOrDefault(l => l.StartsWith('#')) ?? "";
                var m = CalibrationTitle.Match(first);
                if (!m.Success) continue;
                if (Section(text, "Verdict").Contains("accepted", StringComparison.OrdinalIgnoreCase))
                    accepted.Add(m.Groups["hash"].Value);
            }

        var result = new List<CodebookVersion>();
        foreach (var file in Matches(repoRoot, path!, null, null))
        {
            var hash = Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(file))).ToLowerInvariant();
            var questions = Section(File.ReadAllText(file), "Questions")
                .Replace("\r\n", "\n").Split('\n')
                .Select(l => l.Trim().TrimStart('-', '*').Trim())
                .Where(l => l.Length > 0)
                .ToList();
            var calibrated = accepted.Any(hash.StartsWith);
            result.Add(new CodebookVersion(Path.GetRelativePath(repoRoot, file).Replace('\\', '/'), hash, questions, calibrated));
        }
        return result;
    }

    sealed record Round(string Study, IReadOnlyList<string> Questions);

    static IReadOnlyList<Round> ReadRounds(string repoRoot, SkillDocument doc)
    {
        var row = doc.Artifact(WellKnown.VerificationArtifact);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _)) return [];
        var result = new List<Round>();
        foreach (var file in Matches(repoRoot, path!, null, null))
        {
            var questions = Section(File.ReadAllText(file), "Questions answered")
                .Replace("\r\n", "\n").Split('\n')
                .Select(l => l.Trim().TrimStart('-', '*').Trim())
                .Where(l => l.Length > 0)
                .ToList();
            var study = Path.GetFileName(Path.GetDirectoryName(file)!)!;
            result.Add(new Round(study, questions));
        }
        return result;
    }

    /// <summary>The body under a <c>## heading</c>, up to the next heading of any level.</summary>
    public static string Section(string text, string heading)
    {
        var lines = text.Replace("\r\n", "\n").Split('\n');
        var sb = new StringBuilder();
        var inside = false;
        foreach (var line in lines)
        {
            var t = line.Trim();
            if (t.StartsWith('#'))
            {
                if (inside) break;
                inside = t.TrimStart('#').Trim().Equals(heading, StringComparison.Ordinal);
                continue;
            }
            if (inside) sb.Append(line).Append('\n');
        }
        return sb.ToString();
    }

    // ---- hypotheses ----

    static void Hypotheses(StringBuilder sb, string repoRoot, SkillDocument doc, IReadOnlyList<Question> questions)
    {
        sb.Append("## Hypotheses\n\n");
        var row = doc.Artifact(WellKnown.HypothesisStatus) ?? doc.Artifacts.FirstOrDefault(a => WellKnown.HypothesisArtifacts.Contains(a.Id));
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _))
        {
            sb.Append("No hypothesis artifact row with a parseable path; the files cannot be located.\n\n");
            return;
        }
        var prefix = path!.FixedPrefix();
        if (!Directory.Exists(Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar))))
        {
            sb.Append($"Hypothesis files absent: `{prefix}/` does not exist.\n\n");
            return;
        }

        var files = Matches(repoRoot, path, null, null);
        if (files.Count == 0) { sb.Append($"No hypothesis files under `{prefix}/`.\n\n"); return; }

        sb.Append("Status as authored in the frontmatter; \"entries imply\" recomputed from the entries after the " +
                  "last iteration line (a challenging entry → challenged, else an evidence entry → evidenced, else " +
                  "untested); whether a challenge is resolved is not derived.\n\n");
        sb.Append("| id | slug | status | baselined | entries imply | open questions naming it |\n|---|---|---|---|---|---|\n");
        foreach (var file in files)
        {
            var h = ParseHypothesis(file);
            if (h is null) continue;
            var naming = questions.Where(q => q.IsOpen && q.Hypotheses.Contains(h.Id))
                .Select(q => $"{q.Corpus}: {q.Title}").ToList();
            sb.Append("| ").Append(h.Id.ToString("000"))
              .Append(" | ").Append(h.Slug)
              .Append(" | ").Append(h.Status)
              .Append(" | ").Append(h.Baselined)
              .Append(" | ").Append(h.Implied == h.Status ? h.Implied : $"{h.Implied} — MISMATCH")
              .Append(" | ").Append(naming.Count == 0 ? "—" : string.Join("; ", naming).Replace("|", "\\|"))
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    public static Hypothesis? ParseHypothesis(string file)
    {
        var text = File.ReadAllText(file).Replace("\r\n", "\n");
        var lines = text.Split('\n');
        if (lines.Length == 0 || lines[0].Trim() != "---") return null;

        var fm = new Dictionary<string, string>(StringComparer.Ordinal);
        var i = 1;
        for (; i < lines.Length && lines[i].Trim() != "---"; i++)
        {
            var colon = lines[i].IndexOf(':');
            if (colon > 0) fm[lines[i][..colon].Trim()] = lines[i][(colon + 1)..].Trim();
        }
        if (!fm.TryGetValue("id", out var idText) || !int.TryParse(idText, out var id)) return null;

        var record = Section(text, "Record");
        var afterIteration = new List<string>();
        foreach (var line in record.Split('\n'))
        {
            var t = line.Trim();
            if (!t.StartsWith("- ", StringComparison.Ordinal)) continue;
            if (t.StartsWith("- iteration", StringComparison.Ordinal)) { afterIteration.Clear(); continue; }
            afterIteration.Add(t);
        }
        var evidence = afterIteration.Where(l => l.StartsWith("- evidence", StringComparison.Ordinal)).ToList();
        var implied = evidence.Any(l => l.Contains("[challenging]", StringComparison.Ordinal)) ? "challenged"
            : evidence.Count > 0 ? "evidenced"
            : "untested";

        var name = Path.GetFileNameWithoutExtension(file);
        var dash = name.IndexOf('-');
        var slug = dash >= 0 ? name[(dash + 1)..] : name;
        return new Hypothesis(id, slug, fm.GetValueOrDefault("status", ""), fm.GetValueOrDefault("baselined", ""), implied);
    }
}
