using System.Text;
using System.Text.RegularExpressions;
using StoryPlanner.BatchFiles;

namespace StoryPlanner.DocIntegrity;

/// <summary>
/// Writes <c>state.md</c>: what is here, read from the study registry and the files on
/// disk, never what to do next. Its sections, ruled 2026-09-05, brought to the study folders on
/// 2026-09-09 and to the single question list and the pipeline directions on 2026-09-13:
///
/// - per study, the study-scoped artifacts present (paths from the Artifacts table,
///   placeholders as wildcards), its batches with their kind and whether executed and
///   tallied, and the furthest process in chain order whose study-scoped writes all exist;
/// - per iteration, its re-verify batches;
/// - per set of pipeline directions, the referee's and claiming's, each version with its hash,
///   the accepted version and the model its calibration batch ran under, and its calibration
///   batches (d-2026-09-13-58);
/// - the open questions of the one list, each with the calibrated directions versions whose
///   frontmatter names it and the verifications whose standing findings name it
///   (d-2026-09-13-38);
/// - per hypothesis, the status and baselined its entries after the last <c>iteration</c> line
///   imply.
///
/// Where the files a section needs are absent, the section says absent, never empty. Whether a
/// challenging entry is resolved is not derived: the record has no entry kind for it.
///
/// Every section reads through <see cref="Matches"/>, which resolves an artifact's pattern
/// against the files on disk under one directory. Since <c>&lt;container&gt;</c> is never
/// substituted, every batch-scoped class (definition, index, items, results) shares the same
/// fixed-prefix directory regardless of which study asks for it, so <see cref="Build"/> walks
/// that directory, and every study-scoped one, exactly once per render and caches the listing
/// (<see cref="WalkResult"/>, <see cref="Walk"/>), rather than re-walking per artifact per study
/// (2026-09-27). The walk itself is bounded the same way: it never descends into an
/// <c>attempts</c> folder (the runner's per-call stream logs; no artifact class lives there) and
/// it does not enumerate inside an <c>items</c> or <c>results</c> folder (directory classes with
/// no file class inside), so a study with tens of thousands of attempt and item files costs the
/// same to list as one with none.
/// </summary>
public static class StateBuilder
{
    /// <summary>
    /// Chain membership by study type, from schemas/study-registry-schema.md. A closed set
    /// here because the registry names types, not chains; an activity a chain names that the
    /// tables do not carry is skipped and said so.
    /// </summary>
    static readonly string[] ExplorationChain =
        ["preparing-an-exploration", "conducting-an-exploration", "reviewing-leads"];

    static readonly string[] VerificationChain =
        ["preparing-a-verification", "conducting-a-verification", "reviewing-findings",
         "surfacing-candidates", "promoting-refereed-candidates"];

    /// <summary>The container of the pipeline directions' folders, and the sets it holds (d-2026-09-13-55).</summary>
    const string PipelineContainer = "pipeline";
    static readonly string[] PipelineSets = [StudyKinds.RefereeFolder, StudyKinds.ClaimingFolder];

    /// <summary>One registry entry: the id, which is all the registry authors (d-2026-09-14-9 to -11); the type is its prefix.</summary>
    public sealed record Study(string Id)
    {
        public string? Type => Registry.TypeOf(Id);
    }

    /// <summary>One question entry: its slug and whether a withdrawn line sits beneath it. Cited as questions/slug.</summary>
    public sealed record Question(string Slug, bool Withdrawn)
    {
        public bool IsOpen => !Withdrawn;
        public string Cite => $"{Questions.Prefix}/{Slug}";
    }

    /// <summary>One directions version on disk: where, its body hash, the questions its frontmatter names, and whether an accepting calibration exists at its hash.</summary>
    public sealed record DirectionsVersion(string RelativePath, string Hash, IReadOnlyList<string> Questions, bool Calibrated)
    {
        /// <summary>Folder and version without the extension, at the short hash: the form an evidence entry cites.</summary>
        public string Cite => $"{RelativePath[..^Path.GetExtension(RelativePath).Length]}@{Hash[..6]}";
    }

    public sealed record Hypothesis(int Id, string Slug, string Status, string Baselined, string Implied);

    public static string Build(string repoRoot, SkillDocument doc, bool forced = false)
    {
        var sb = new StringBuilder();
        sb.Append("# state.md — generated by process-docs/StoryPlanner.DocIntegrity\n\n");
        sb.Append("Never hand-edited: `render` rewrites this file whole from the study registry, the question " +
                  "list, the hypothesis files, the study folders, the pipeline directions and the directions on " +
                  "disk. What is here, never what to do next; the pick is Brian's.\n\n");
        if (forced)
            sb.Append("> **UNVALIDATED** — written with `--force` while `check` still fails. Not authoritative.\n\n");

        // One walk cache for the whole build (d-2026-09-27): every artifact class that resolves
        // to the same fixed-prefix directory — which, for the batch-scoped classes, is every one
        // of them, since <container> never gets substituted — shares that directory's single
        // bounded walk instead of re-walking it once per study. See Walk.
        var cache = new Dictionary<string, WalkResult>(StringComparer.Ordinal);

        var questions = ReadQuestions(repoRoot, doc, cache, out var questionsNote);
        Studies(sb, repoRoot, doc, cache);
        Iterations(sb, repoRoot, doc, cache);
        PipelineDirections(sb, repoRoot, doc, cache);
        QuestionsSection(sb, repoRoot, doc, questions, questionsNote, cache);
        Hypotheses(sb, repoRoot, doc, cache);
        return sb.ToString();
    }

    // ---- studies ----

    static void Studies(StringBuilder sb, string repoRoot, SkillDocument doc, Dictionary<string, WalkResult> cache)
    {
        sb.Append("## Studies\n\n");
        var row = doc.Artifact(WellKnown.Studies);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var registryPath, out _))
        {
            sb.Append($"No `{WellKnown.Studies}` artifact row with a parseable path; the registry cannot be located.\n\n");
            return;
        }
        var registry = Path.Combine(repoRoot, registryPath!.Pattern.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(registry))
        {
            sb.Append($"Registry absent: `{registryPath.Pattern}` does not exist.\n\n");
            return;
        }

        var studies = ReadRegistry(registry);
        if (studies.Count == 0)
        {
            sb.Append($"Registry `{registryPath.Pattern}` holds no entries.\n\n");
            return;
        }

        foreach (var study in studies)
        {
            sb.Append($"### {study.Id}\n\n");
            sb.Append($"- type: {study.Type ?? "?"}\n");

            var chain = ChainFor(study);
            if (chain is null)
            {
                sb.Append($"- chain: no type prefix on '{study.Id}'; nothing derived\n\n");
                continue;
            }
            var missing = chain.Where(a => !doc.Activities.Any(x => x.Id == a)).ToList();
            var processes = chain.SelectMany(doc.ProcessesOf).ToList();
            var folder = StudyFolder(study.Id);

            var scoped = processes.SelectMany(p => p.Writes).Distinct(StringComparer.Ordinal)
                .Select(doc.Artifact).Where(a => a is not null).Select(a => a!)
                .Where(a => ArtifactPath.TryParse(a.Path, out var ap, out _) && ap!.IsStudyScoped)
                .ToList();

            var present = new Dictionary<string, int>(StringComparer.Ordinal);
            sb.Append("- artifacts present:");
            var any = false;
            foreach (var a in scoped)
            {
                ArtifactPath.TryParse(a.Path, out var ap, out _);
                var count = CountMatches(repoRoot, ap!, folder, cache);
                present[a.Id] = count;
                if (count == 0) continue;
                any = true;
                sb.Append($" {a.Id}");
                if (count > 1) sb.Append($" ({count})");
                if (a.Id == WellKnown.Candidates)
                    foreach (var file in Matches(repoRoot, ap!, folder, cache))
                        sb.Append($" [{CandidateCounts(file)}]");
            }
            sb.Append(any ? "\n" : " none\n");

            Batches(sb, repoRoot, doc, folder, cache);

            string? furthest = null;
            foreach (var p in processes)
            {
                var writes = p.Writes.Where(present.ContainsKey).ToList();
                if (writes.Count == 0) continue;
                if (writes.All(w => present[w] > 0)) furthest = $"{p.Id} ({p.Activity})";
            }
            sb.Append($"- furthest process whose study-scoped writes all exist: {furthest ?? "none"}\n");
            if (missing.Count > 0)
                sb.Append($"- chain activities the tables do not carry, skipped: {string.Join(" ", missing)}\n");
            sb.Append('\n');
        }
    }

    // ---- iterations ----

    /// <summary>
    /// Per iteration folder (d-2026-09-11-4): an iteration's re-verification is no study, but its
    /// folder mirrors a study's under <c>docs/v3-framework/iterations/</c>, so the render scans
    /// that sibling of <c>studies/</c> for <c>iteration-of-*</c> folders and shows each one's
    /// batches, the same way a study's are shown. An iteration is not in the registry; its
    /// existence and ordinal are read from the folder name.
    /// </summary>
    static void Iterations(StringBuilder sb, string repoRoot, SkillDocument doc, Dictionary<string, WalkResult> cache)
    {
        sb.Append("## Iterations\n\n");
        var dir = Path.Combine(repoRoot, "docs", "v3-framework", "iterations");
        if (!Directory.Exists(dir)) { sb.Append("None: `docs/v3-framework/iterations/` does not exist.\n\n"); return; }
        var folders = Directory.GetDirectories(dir)
            .Select(Path.GetFileName)
            .Where(n => n is not null && n.StartsWith(IterationPrefix, StringComparison.Ordinal))
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();
        if (folders.Count == 0) { sb.Append("None.\n\n"); return; }
        foreach (var slug in folders)
        {
            sb.Append($"### {slug}\n\n");
            var (hypothesis, ordinal) = IterationParts(slug!);
            sb.Append($"- of hypothesis: {hypothesis ?? "?"} · iteration: {(ordinal?.ToString() ?? "?")}\n");
            Batches(sb, repoRoot, doc, slug!, cache);
            sb.Append('\n');
        }
    }

    const string IterationPrefix = "iteration-of-";

    // ---- pipeline directions ----

    /// <summary>
    /// Per set of pipeline directions (d-2026-09-13-58), from its folder under
    /// <c>docs/v3-framework/pipeline/</c>: each directions version in order with its body hash,
    /// marked where an accepting calibration beside it carries that hash; the last accepted
    /// version and the model the batches under it ran; and the folder's calibration batches.
    /// </summary>
    static void PipelineDirections(StringBuilder sb, string repoRoot, SkillDocument doc, Dictionary<string, WalkResult> cache)
    {
        sb.Append("## Pipeline directions\n\n");
        foreach (var set in PipelineSets)
        {
            sb.Append($"### {set}\n\n");
            var relative = $"docs/v3-framework/{PipelineContainer}/{set}";
            var dir = Path.Combine(repoRoot, relative.Replace('/', Path.DirectorySeparatorChar));
            if (!Directory.Exists(dir)) { sb.Append($"Absent: `{relative}/` does not exist.\n\n"); continue; }

            var accepted = Directory.GetFiles(dir, "calibration-*.md").Select(CalibrationFile.Read)
                .Where(c => c.TitleParsed && c.Accepted).Select(c => c.Hash!).ToList();
            var versions = Directory.GetFiles(dir, "directions-*.md")
                .Select(f => (File: f, N: DirectionsFile.VersionOf(Path.GetFileName(f))))
                .Where(v => v.N is not null).OrderBy(v => v.N)
                .Select(v => (v.File, N: v.N!.Value, Hash: DirectionsFile.Read(v.File).BodyHash))
                .ToList();
            if (versions.Count == 0) sb.Append("- versions: none\n");
            else
            {
                sb.Append("- versions:");
                foreach (var v in versions)
                    sb.Append($" directions-{v.N}@{v.Hash[..6]}{(accepted.Any(h => Hashing.Cites(h, v.Hash)) ? " (accepted)" : "")}");
                sb.Append('\n');
                var current = versions.LastOrDefault(v => accepted.Any(h => Hashing.Cites(h, v.Hash)));
                if (current.File is null) sb.Append("- accepted: none\n");
                else
                {
                    var models = DefinitionsUnder(Path.Combine(dir, "batches"))
                        .Where(d => d.DirectionsPath is not null && Path.GetFullPath(d.DirectionsPath) == Path.GetFullPath(current.File) && d.Model is not null)
                        .Select(d => d.Model!).Distinct(StringComparer.Ordinal).ToList();
                    sb.Append($"- accepted: directions-{current.N} · model: {(models.Count == 0 ? "?" : string.Join(" ", models))}\n");
                }
            }
            Batches(sb, repoRoot, doc, set, cache);
            sb.Append('\n');
        }
    }

    static IEnumerable<DefinitionFile> DefinitionsUnder(string batchesDir)
    {
        if (!Directory.Exists(batchesDir)) yield break;
        foreach (var path in Directory.GetDirectories(batchesDir).Select(d => Path.Combine(d, "definition.md")).Where(File.Exists).OrderBy(p => p, StringComparer.Ordinal))
        {
            DefinitionFile d;
            try { d = DefinitionFile.Read(path); } catch (IOException) { continue; }
            yield return d;
        }
    }

    /// <summary>The hypothesis file name and ordinal an <c>iteration-of-&lt;hypothesis-file-name&gt;-&lt;N&gt;</c> folder names.</summary>
    public static (string? Hypothesis, int? Ordinal) IterationParts(string slug)
    {
        if (!slug.StartsWith(IterationPrefix, StringComparison.Ordinal)) return (null, null);
        var rest = slug[IterationPrefix.Length..];
        var dash = rest.LastIndexOf('-');
        if (dash < 0 || !int.TryParse(rest[(dash + 1)..], out var n)) return (rest.Length == 0 ? null : rest, null);
        return (rest[..dash], n);
    }

    /// <summary>The study's batches from their definitions: kind, directions version, executed (a calls file), tallied.</summary>
    static void Batches(StringBuilder sb, string repoRoot, SkillDocument doc, string folder, Dictionary<string, WalkResult> cache)
    {
        var row = doc.Artifact(WellKnown.Definition);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var ap, out _)) return;
        var definitions = Matches(repoRoot, ap!, folder, cache);
        if (definitions.Count == 0) { sb.Append("- batches: none\n"); return; }
        sb.Append("- batches:");
        foreach (var path in definitions)
        {
            DefinitionFile d;
            try { d = DefinitionFile.Read(path); } catch (IOException) { continue; }
            var directions = d.DirectionsPath is null ? "?" : Path.GetFileNameWithoutExtension(d.DirectionsPath);
            var calls = File.Exists(d.CallsPath) ? CallsFile.Read(d.CallsPath) : null;
            var items = File.Exists(d.IndexPath) ? IndexFile.Read(d.IndexPath).Rows.Count : 0;
            var done = calls is null ? 0 : calls.Entries.Where(e => e.Succeeded).Select(e => e.Item).Distinct().Count();
            var stage = File.Exists(d.TallyPath) ? "tallied" : calls is not null ? (done == items && items > 0 ? "executed" : $"executing ({done}/{items})") : items > 0 ? "itemized" : "defined";
            sb.Append($" {d.Batch} [{d.Kind ?? "-"}, {directions}, {stage}]");
        }
        sb.Append('\n');
    }

    /// <summary>The registry's entries in order: each <c>- &lt;id&gt;</c> line after the title (d-2026-09-14-11); anything else is the checker's to report.</summary>
    static IReadOnlyList<Study> ReadRegistry(string path)
        => File.ReadAllLines(path)
            .Where(l => l.StartsWith("- ", StringComparison.Ordinal))
            .Select(l => new Study(l[2..].Trim()))
            .Where(s => s.Id.Length > 0)
            .ToList();

    static string[]? ChainFor(Study study) => study.Type switch
    {
        "exploration" => ExplorationChain,
        "verification" => VerificationChain,
        _ => null,
    };

    /// <summary>A study's folder is its registry id (SKILL.md § Artifacts); the pipeline directions have their own folders.</summary>
    public static string StudyFolder(string studyId) => studyId;

    /// <summary>
    /// The promoted, declined and pending counts over a generated candidates.md (d-2026-09-10-9),
    /// read from the status the view materialises per diagnostic candidate — promoted where a
    /// hypothesis record cites it, declined from declined-candidates.md, else pending
    /// (d-2026-09-10-7). Non-diagnostic claims carry no status and are not counted.
    /// </summary>
    static string CandidateCounts(string file)
    {
        int promoted = 0, declined = 0, pending = 0;
        foreach (var raw in File.ReadAllText(file).Replace("\r\n", "\n").Split('\n'))
        {
            var l = raw.Trim();
            if (l == "- status: promoted") promoted++;
            else if (l == "- status: declined") declined++;
            else if (l == "- status: pending") pending++;
        }
        return $"{promoted} promoted, {declined} declined, {pending} pending";
    }

    // ---- files on disk matching an artifact's pattern ----

    /// <summary>
    /// One directory's bounded listing: every file and directory reachable from it without
    /// descending into an <c>attempts</c> folder — the runner's per-call stream logs; no
    /// artifact class lives there (confirmed against SKILL.md § Artifacts and the patterns in
    /// <see cref="ArtifactPath"/>) — and without enumerating inside an <c>items</c> or
    /// <c>results</c> folder, the two directory classes, since no file class lives inside
    /// either. Their own presence and non-emptiness is decided by the regex match in
    /// <see cref="Matches"/>, not during the walk, so listing them here needs no more than
    /// finding them.
    /// </summary>
    public sealed record WalkResult(IReadOnlyList<string> Files, IReadOnlyList<string> Dirs);

    static WalkResult Walk(string absoluteDir)
    {
        var files = new List<string>();
        var dirs = new List<string>();

        void Visit(string dir)
        {
            IEnumerable<string> subdirs;
            try { subdirs = Directory.EnumerateDirectories(dir); }
            catch (IOException) { return; }
            catch (UnauthorizedAccessException) { return; }

            foreach (var sub in subdirs)
            {
                var name = Path.GetFileName(sub);
                if (string.Equals(name, "attempts", StringComparison.OrdinalIgnoreCase)) continue;
                dirs.Add(sub);
                if (string.Equals(name, "items", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(name, "results", StringComparison.OrdinalIgnoreCase)) continue;
                Visit(sub);
            }
            try { files.AddRange(Directory.EnumerateFiles(dir)); }
            catch (IOException) { }
            catch (UnauthorizedAccessException) { }
        }

        Visit(absoluteDir);
        return new WalkResult(files, dirs);
    }

    /// <summary>
    /// Every file on disk an artifact's pattern matches. A fresh, one-call cache: callers inside
    /// one <see cref="Build"/> use the cache-carrying overload below instead, so the same root
    /// (which every batch-scoped class shares, since <c>&lt;container&gt;</c> is never
    /// substituted) is walked once for the whole render rather than once per call.
    /// </summary>
    public static IReadOnlyList<string> Matches(string repoRoot, ArtifactPath path, string? studyFolder)
        => Matches(repoRoot, path, studyFolder, new Dictionary<string, WalkResult>(StringComparer.Ordinal));

    static IReadOnlyList<string> Matches(string repoRoot, ArtifactPath path, string? studyFolder, Dictionary<string, WalkResult> cache)
    {
        if (path.NoSinglePattern) return [];
        var prefix = path.FixedPrefix(studyFolder);
        var dir = prefix.Length == 0 ? repoRoot : Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar));
        if (!Directory.Exists(dir)) return [];

        if (!cache.TryGetValue(dir, out var walk))
        {
            walk = Walk(dir);
            cache[dir] = walk;
        }

        var regex = path.ToRegex(studyFolder);
        IEnumerable<string> entries = path.IsDirectory ? walk.Dirs : walk.Files;
        entries = entries.Where(e => regex.IsMatch(Path.GetRelativePath(repoRoot, e).Replace('\\', '/')));
        if (path.IsDirectory)
            entries = entries.Where(d => Directory.EnumerateFileSystemEntries(d, "*", SearchOption.AllDirectories).Any());

        return entries
            .OrderBy(e => e, StringComparer.Ordinal)
            .ToList();
    }

    static int CountMatches(string repoRoot, ArtifactPath path, string? studyFolder, Dictionary<string, WalkResult> cache)
        => Matches(repoRoot, path, studyFolder, cache).Count;

    // ---- questions ----

    static IReadOnlyList<Question> ReadQuestions(string repoRoot, SkillDocument doc, Dictionary<string, WalkResult> cache, out string? note)
    {
        note = null;
        var row = doc.Artifact(WellKnown.QuestionList);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _))
        {
            note = $"No `{WellKnown.QuestionList}` artifact row with a parseable path; the list cannot be located.";
            return [];
        }
        var files = Matches(repoRoot, path!, null, cache);
        if (files.Count == 0)
        {
            note = $"Question list absent: nothing matches `{path!.Pattern}`.";
            return [];
        }

        var questions = new List<Question>();
        foreach (var file in files)
            questions.AddRange(ParseQuestions(File.ReadAllText(file)));
        if (questions.Count == 0) note = $"The question list `{path!.Pattern}` holds no entries.";
        return questions;
    }

    public static IReadOnlyList<Question> ParseQuestions(string text)
    {
        var result = new List<Question>();
        string? slug = null;
        var withdrawn = false;

        void Flush()
        {
            if (slug is not null) result.Add(new Question(slug, withdrawn));
            slug = null; withdrawn = false;
        }

        foreach (var raw in text.Replace("\r\n", "\n").Split('\n'))
        {
            var line = raw.Trim();
            if (line.StartsWith("### ", StringComparison.Ordinal))
            {
                Flush();
                var heading = line[4..].Trim(); // "questions/<slug>", the citation token (d-2026-09-07-31, -09-13-38)
                slug = heading[(heading.IndexOf('/') + 1)..];
                continue;
            }
            if (line.StartsWith("## ", StringComparison.Ordinal) || line.StartsWith("# ", StringComparison.Ordinal)) { Flush(); continue; }
            if (slug is null) continue;
            if (line.StartsWith("- withdrawn:", StringComparison.Ordinal)) withdrawn = true;
            else if (line.StartsWith("- reinstated:", StringComparison.Ordinal)) withdrawn = false;
        }
        Flush();
        return result;
    }

    static void QuestionsSection(StringBuilder sb, string repoRoot, SkillDocument doc, IReadOnlyList<Question> questions, string? note, Dictionary<string, WalkResult> cache)
    {
        sb.Append("## Questions\n\n");
        if (note is not null) { sb.Append(note).Append("\n\n"); if (questions.Count == 0) return; }

        var versions = ReadDirections(repoRoot, doc, cache);
        var verifications = ReadVerifications(repoRoot, doc, cache);

        var open = questions.Where(q => q.IsOpen).ToList();
        sb.Append($"{open.Count} open, {questions.Count - open.Count} withdrawn.\n\n");
        if (open.Count == 0) return;
        sb.Append("| question | covered by (calibrated directions) | answered by (verification) |\n|---|---|---|\n");
        foreach (var q in open)
        {
            var covering = versions.Where(c => c.Calibrated && c.Questions.Contains(q.Cite, StringComparer.Ordinal)).Select(c => c.Cite).ToList();
            var answering = verifications.Where(v => v.Questions.Contains(q.Cite, StringComparer.Ordinal)).Select(v => v.Study).ToList();
            sb.Append("| ").Append(q.Slug)
              .Append(" | ").Append(covering.Count == 0 ? "nothing" : string.Join(" ", covering))
              .Append(" | ").Append(answering.Count == 0 ? "nothing" : string.Join(" ", answering))
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    /// <summary>
    /// Every directions version the table locates, with its body hash and the questions its
    /// frontmatter names; calibrated when a calibration file beside it, or one a definition
    /// names, is titled with its hash and accepts it.
    /// </summary>
    public static IReadOnlyList<DirectionsVersion> ReadDirections(string repoRoot, SkillDocument doc, Dictionary<string, WalkResult>? cache = null)
    {
        cache ??= new Dictionary<string, WalkResult>(StringComparer.Ordinal);
        var row = doc.Artifact(WellKnown.Directions);
        var calRow = doc.Artifact(WellKnown.Calibration);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _)) return [];

        var accepted = new HashSet<string>(StringComparer.Ordinal); // hashes (possibly prefixes) with an accepting calibration
        if (calRow is not null && ArtifactPath.TryParse(calRow.Path, out var calPath, out _))
            foreach (var file in Matches(repoRoot, calPath!, null, cache))
            {
                var cal = CalibrationFile.Read(file);
                if (cal.TitleParsed && cal.Accepted) accepted.Add(cal.Hash!);
            }
        // The pipeline directions' calibrations, reached only by reference from definitions.
        if (doc.Artifact(WellKnown.Definition) is { } defRow && ArtifactPath.TryParse(defRow.Path, out var defPath, out _))
            foreach (var file in Matches(repoRoot, defPath!, null, cache))
            {
                DefinitionFile d;
                try { d = DefinitionFile.Read(file); } catch (IOException) { continue; }
                if (d.CalibrationPath is not null && File.Exists(d.CalibrationPath))
                {
                    var cal = CalibrationFile.Read(d.CalibrationPath);
                    if (cal.TitleParsed && cal.Accepted) accepted.Add(cal.Hash!);
                }
            }

        var files = Matches(repoRoot, path!, null, cache).ToList();
        foreach (var set in PipelineSets)
        {
            var dir = Path.Combine(repoRoot, "docs", "v3-framework", PipelineContainer, set);
            if (Directory.Exists(dir)) files.AddRange(Directory.GetFiles(dir, "directions-*.md").OrderBy(f => f, StringComparer.Ordinal));
        }

        var result = new List<DirectionsVersion>();
        foreach (var file in files.Distinct(StringComparer.OrdinalIgnoreCase))
        {
            var d = DirectionsFile.Read(file);
            var calibrated = accepted.Any(h => Hashing.Cites(h, d.BodyHash));
            result.Add(new DirectionsVersion(Path.GetRelativePath(repoRoot, file).Replace('\\', '/'), d.BodyHash, d.Questions, calibrated));
        }
        return result;
    }

    sealed record Verification(string Study, IReadOnlyList<string> Questions);

    /// <summary>A question is answered when a standing finding names it (d-2026-09-09-16): read from every findings file the table locates.</summary>
    static IReadOnlyList<Verification> ReadVerifications(string repoRoot, SkillDocument doc, Dictionary<string, WalkResult> cache)
    {
        var row = doc.Artifact(WellKnown.Findings);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _)) return [];
        var result = new List<Verification>();
        foreach (var file in Matches(repoRoot, path!, null, cache))
        {
            var questions = FindingsChecker.AnsweredQuestions(File.ReadAllText(file));
            var study = Path.GetFileName(Path.GetDirectoryName(file)!)!;
            result.Add(new Verification(study, questions));
        }
        return result;
    }

    /// <summary>The body under a <c>## heading</c>, up to the next heading of any level.</summary>
    public static string Section(string text, string heading)
    {
        var lines = text.Replace("\r\n", "\n").Split('\n');
        var sb = new StringBuilder();
        var inside = false;
        var inFence = false;
        foreach (var line in lines)
        {
            var t = line.Trim();
            if (t.StartsWith("```", StringComparison.Ordinal)) { inFence = !inFence; if (inside) sb.Append(line).Append('\n'); continue; }
            if (!inFence && t.StartsWith('#'))
            {
                if (inside) break;
                inside = t.TrimStart('#').Trim().Equals(heading, StringComparison.Ordinal);
                continue;
            }
            if (inside) sb.Append(line).Append('\n');
        }
        return sb.ToString();
    }

    // ---- hypotheses ----

    static void Hypotheses(StringBuilder sb, string repoRoot, SkillDocument doc, Dictionary<string, WalkResult> cache)
    {
        sb.Append("## Hypotheses\n\n");
        var row = doc.Artifact(WellKnown.HypothesisRecord) ?? doc.Artifacts.FirstOrDefault(a => WellKnown.HypothesisArtifacts.Contains(a.Id));
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _))
        {
            sb.Append("No hypothesis artifact row with a parseable path; the files cannot be located.\n\n");
            return;
        }
        var prefix = path!.FixedPrefix();
        if (!Directory.Exists(Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar))))
        {
            sb.Append($"Hypothesis files absent: `{prefix}/` does not exist.\n\n");
            return;
        }

        var files = Matches(repoRoot, path, null, cache);
        if (files.Count == 0) { sb.Append($"No hypothesis files under `{prefix}/`.\n\n"); return; }

        sb.Append("Nothing here is authored: status and baselined are read from the entries below the last " +
                  "`### iteration`, which is the wording boundary — a challenging entry → challenged, else an " +
                  "evidence entry → evidenced, else untested; whether a challenge is resolved is not derived " +
                  "(d-2026-09-11-12).\n\n");
        sb.Append("| id | slug | status | baselined |\n|---|---|---|---|\n");
        foreach (var file in files)
        {
            var h = ParseHypothesis(file);
            if (h is null) continue;
            sb.Append("| ").Append(h.Id.ToString("000"))
              .Append(" | ").Append(h.Slug)
              .Append(" | ").Append(h.Status)
              .Append(" | ").Append(h.Baselined)
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    /// <summary>
    /// One hypothesis as state.md shows it. Since d-2026-09-11-12 the file authors nothing
    /// derivable: the id is its file name, and status and baselined are read from the entries
    /// below the last iteration boundary.
    /// </summary>
    public static Hypothesis? ParseHypothesis(string file)
    {
        var name = Path.GetFileNameWithoutExtension(file);
        var dash = name.IndexOf('-');
        if (dash < 3 || !int.TryParse(name[..dash], out var id)) return null;
        var slug = name[(dash + 1)..];

        var text = File.ReadAllText(file).Replace("\r\n", "\n");
        var entries = new List<(string Kind, string Body)>();
        string? kind = null;
        var body = new List<string>();
        foreach (var line in RecordSection(text))
        {
            if (line.StartsWith("### ", StringComparison.Ordinal))
            {
                if (kind is not null) entries.Add((kind, string.Join('\n', body)));
                kind = line[4..].Trim();
                body = [];
                continue;
            }
            if (kind is not null) body.Add(line);
        }
        if (kind is not null) entries.Add((kind, string.Join('\n', body)));

        var lastIteration = entries.FindLastIndex(e => e.Kind == "iteration");
        var current = entries.Skip(lastIteration + 1).ToList();
        var evidence = current.Where(e => e.Kind == "evidence").ToList();
        var status = evidence.Any(e => e.Body.Contains("- tag: challenging", StringComparison.Ordinal)) ? "challenged"
            : evidence.Count > 0 ? "evidenced"
            : "untested";
        var baselined = current.LastOrDefault(e => e.Kind == "baselined").Body is { } b
            ? Keyed(b, "date") ?? "yes"
            : "false";

        return new Hypothesis(id, slug, status, baselined, status);
    }

    /// <summary>
    /// The lines of § Record. Not <see cref="Section"/>: that stops at the next line beginning
    /// `##`, and the record's entries are `### <kind>` headings, which begin that way too.
    /// </summary>
    static IEnumerable<string> RecordSection(string text)
    {
        var inside = false;
        foreach (var line in text.Split('\n'))
        {
            if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                if (inside) yield break;
                inside = line.Trim() == "## Record";
                continue;
            }
            if (inside) yield return line;
        }
    }

    /// <summary>The value of one `- key: value` line of an entry body, or null.</summary>
    static string? Keyed(string body, string key)
        => body.Split('\n')
            .Select(l => l.TrimEnd())
            .FirstOrDefault(l => l.StartsWith($"- {key}: ", StringComparison.Ordinal))?[(key.Length + 4)..];
}
