using System.Text;
using System.Text.RegularExpressions;
using StoryPlanner.BatchFiles;

namespace StoryPlanner.DocIntegrity;

/// <summary>
/// Writes <c>state.md</c>: what is here, read from the study registry and the files on
/// disk, never what to do next. Three sections, ruled 2026-09-05 and brought to the study
/// folders on 2026-09-09:
///
/// - per study, the study-scoped artifacts present (paths from the Artifacts table,
///   placeholders as wildcards), its batches with their kind and whether executed and
///   tallied, and the furthest process in chain order whose study-scoped writes all exist;
/// - per corpus, the open questions, each with the calibrated directions versions whose
///   frontmatter names it and the verifications whose standing findings name it;
/// - per hypothesis, the status and baselined its entries after the last <c>iteration</c> line
///   imply.
///
/// Where the files a section needs are absent, the section says absent, never empty. Whether a
/// challenging entry is resolved is not derived: the record has no entry kind for it.
/// </summary>
public static class StateBuilder
{
    /// <summary>
    /// Chain membership by study type, from schemas/study-registry-schema.md. A closed set
    /// here because the registry names types, not chains; an activity a chain names that the
    /// tables do not carry is skipped and said so.
    /// </summary>
    static readonly string[] ExplorationChain =
        ["preparing-to-explore-a-corpus", "exploring-a-corpus", "reviewing-leads"];

    static readonly string[] VerificationChain =
        ["preparing-to-verify-a-corpus", "verifying-a-corpus", "reviewing-findings",
         "surfacing-candidates", "promoting-refereed-candidates"];

    static readonly string[] AuditChain = ["revising-the-method"];

    public sealed record Study(string Id, string Type, string Corpus, string Go);

    /// <summary>One question entry: its slug and whether a withdrawn line sits beneath it. Cited as corpus/slug.</summary>
    public sealed record Question(string Corpus, string Slug, bool Withdrawn)
    {
        public bool IsOpen => !Withdrawn;
        public string Cite => $"{Corpus}/{Slug}";
    }

    /// <summary>One directions version on disk: where, its body hash, the questions its frontmatter names, and whether an accepting calibration exists at its hash.</summary>
    public sealed record DirectionsVersion(string RelativePath, string Hash, IReadOnlyList<string> Questions, bool Calibrated)
    {
        /// <summary>Folder and version without the extension, at the short hash: the form an evidence entry cites.</summary>
        public string Cite => $"{RelativePath[..^Path.GetExtension(RelativePath).Length]}@{Hash[..6]}";
    }

    public sealed record Hypothesis(int Id, string Slug, string Status, string Baselined, string Implied);

    public static string Build(string repoRoot, SkillDocument doc, bool forced = false)
    {
        var sb = new StringBuilder();
        sb.Append("# state.md — generated by process-docs/StoryPlanner.DocIntegrity\n\n");
        sb.Append("Never hand-edited: `render` rewrites this file whole from the study registry, the question " +
                  "lists, the hypothesis files, the study folders and the directions on disk. What is here, " +
                  "never what to do next; the pick is Brian's.\n\n");
        if (forced)
            sb.Append("> **UNVALIDATED** — written with `--force` while `check` still fails. Not authoritative.\n\n");

        var questions = ReadQuestions(repoRoot, doc, out var questionsNote);
        Studies(sb, repoRoot, doc);
        Iterations(sb, repoRoot, doc);
        Corpora(sb, repoRoot, doc, questions, questionsNote);
        Hypotheses(sb, repoRoot, doc);
        return sb.ToString();
    }

    // ---- studies ----

    static void Studies(StringBuilder sb, string repoRoot, SkillDocument doc)
    {
        sb.Append("## Studies\n\n");
        var row = doc.Artifact(WellKnown.Studies);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var registryPath, out _))
        {
            sb.Append($"No `{WellKnown.Studies}` artifact row with a parseable path; the registry cannot be located.\n\n");
            return;
        }
        var registry = Path.Combine(repoRoot, registryPath!.Pattern.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(registry))
        {
            sb.Append($"Registry absent: `{registryPath.Pattern}` does not exist.\n\n");
            return;
        }

        var studies = ReadRegistry(registry);
        if (studies.Count == 0)
        {
            sb.Append($"Registry `{registryPath.Pattern}` holds no rows.\n\n");
            return;
        }

        foreach (var study in studies)
        {
            sb.Append($"### {study.Id}\n\n");
            sb.Append($"- type: {study.Type} · corpus: {study.Corpus} · go: {study.Go}\n");

            var chain = ChainFor(study);
            if (chain is null)
            {
                sb.Append($"- chain: unknown type '{study.Type}'; nothing derived\n\n");
                continue;
            }
            var missing = chain.Where(a => !doc.Activities.Any(x => x.Id == a)).ToList();
            var processes = chain.SelectMany(doc.ProcessesOf).ToList();
            var folder = StudyFolder(study.Id);

            var scoped = processes.SelectMany(p => p.Writes).Distinct(StringComparer.Ordinal)
                .Select(doc.Artifact).Where(a => a is not null).Select(a => a!)
                .Where(a => ArtifactPath.TryParse(a.Path, out var ap, out _) && ap!.IsStudyScoped)
                .ToList();

            var present = new Dictionary<string, int>(StringComparer.Ordinal);
            sb.Append("- artifacts present:");
            var any = false;
            foreach (var a in scoped)
            {
                ArtifactPath.TryParse(a.Path, out var ap, out _);
                var count = CountMatches(repoRoot, ap!, folder, study.Corpus);
                present[a.Id] = count;
                if (count == 0) continue;
                any = true;
                sb.Append($" {a.Id}");
                if (count > 1) sb.Append($" ({count})");
                if (a.Id == WellKnown.Candidates)
                    foreach (var file in Matches(repoRoot, ap!, folder, study.Corpus))
                        sb.Append($" [{CandidateCounts(file)}]");
            }
            sb.Append(any ? "\n" : " none\n");

            Batches(sb, repoRoot, doc, folder);

            string? furthest = null;
            foreach (var p in processes)
            {
                var writes = p.Writes.Where(present.ContainsKey).ToList();
                if (writes.Count == 0) continue;
                if (writes.All(w => present[w] > 0)) furthest = $"{p.Id} ({p.Activity})";
            }
            sb.Append($"- furthest process whose study-scoped writes all exist: {furthest ?? "none"}\n");
            if (missing.Count > 0)
                sb.Append($"- chain activities the tables do not carry, skipped: {string.Join(" ", missing)}\n");
            sb.Append('\n');
        }
    }

    // ---- iterations ----

    /// <summary>
    /// Per iteration folder (d-2026-09-11-4): an iteration's re-verification is no study, but its
    /// folder mirrors a study's under <c>docs/v3-framework/iterations/</c>, so the render scans
    /// that sibling of <c>studies/</c> for <c>iteration-of-*</c> folders and shows each one's
    /// batches, the same way a study's are shown. An iteration is not in the registry; its
    /// existence and ordinal are read from the folder name.
    /// </summary>
    static void Iterations(StringBuilder sb, string repoRoot, SkillDocument doc)
    {
        sb.Append("## Iterations\n\n");
        var dir = Path.Combine(repoRoot, "docs", "v3-framework", "iterations");
        if (!Directory.Exists(dir)) { sb.Append("None: `docs/v3-framework/iterations/` does not exist.\n\n"); return; }
        var folders = Directory.GetDirectories(dir)
            .Select(Path.GetFileName)
            .Where(n => n is not null && n.StartsWith(IterationPrefix, StringComparison.Ordinal))
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();
        if (folders.Count == 0) { sb.Append("None.\n\n"); return; }
        foreach (var slug in folders)
        {
            sb.Append($"### {slug}\n\n");
            var (hypothesis, ordinal) = IterationParts(slug!);
            sb.Append($"- of hypothesis: {hypothesis ?? "?"} · iteration: {(ordinal?.ToString() ?? "?")}\n");
            Batches(sb, repoRoot, doc, slug!);
            sb.Append('\n');
        }
    }

    const string IterationPrefix = "iteration-of-";

    /// <summary>The hypothesis file name and ordinal an <c>iteration-of-&lt;hypothesis-file-name&gt;-&lt;N&gt;</c> folder names.</summary>
    public static (string? Hypothesis, int? Ordinal) IterationParts(string slug)
    {
        if (!slug.StartsWith(IterationPrefix, StringComparison.Ordinal)) return (null, null);
        var rest = slug[IterationPrefix.Length..];
        var dash = rest.LastIndexOf('-');
        if (dash < 0 || !int.TryParse(rest[(dash + 1)..], out var n)) return (rest.Length == 0 ? null : rest, null);
        return (rest[..dash], n);
    }

    /// <summary>The study's batches from their definitions: kind, directions version, executed (a calls file), tallied.</summary>
    static void Batches(StringBuilder sb, string repoRoot, SkillDocument doc, string folder)
    {
        var row = doc.Artifact(WellKnown.Definition);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var ap, out _)) return;
        var definitions = Matches(repoRoot, ap!, folder, null);
        if (definitions.Count == 0) { sb.Append("- batches: none\n"); return; }
        sb.Append("- batches:");
        foreach (var path in definitions)
        {
            DefinitionFile d;
            try { d = DefinitionFile.Read(path); } catch (IOException) { continue; }
            var directions = d.DirectionsPath is null ? "?" : Path.GetFileNameWithoutExtension(d.DirectionsPath);
            var calls = File.Exists(d.CallsPath) ? CallsFile.Read(d.CallsPath) : null;
            var items = File.Exists(d.IndexPath) ? IndexFile.Read(d.IndexPath).Rows.Count : 0;
            var done = calls is null ? 0 : calls.Entries.Where(e => e.Succeeded).Select(e => e.Item).Distinct().Count();
            var stage = File.Exists(d.TallyPath) ? "tallied" : calls is not null ? (done == items && items > 0 ? "executed" : $"executing ({done}/{items})") : items > 0 ? "itemized" : "defined";
            sb.Append($" {d.Batch} [{d.Kind ?? "-"}, {directions}, {stage}]");
        }
        sb.Append('\n');
    }

    static IReadOnlyList<Study> ReadRegistry(string path)
    {
        var tables = MapTables.ReadAll(File.ReadAllText(path));
        var table = tables.FirstOrDefault(t =>
            t.Headers.Select(h => h.ToLowerInvariant()).SequenceEqual(["id", "type", "corpus", "go"]));
        if (table is null)
            throw new MapFormatException($"{Path.GetFileName(path)}: no table with columns id | type | corpus | go.");
        return table.Rows.Select(r => new Study(r.Cells[0], r.Cells[1], r.Cells[2], r.Cells[3])).ToList();
    }

    static string[]? ChainFor(Study study) => study.Type switch
    {
        "exploration" => ExplorationChain,
        "verification" => VerificationChain,
        "audit" => AuditChain,
        _ => null,
    };

    /// <summary>A study's folder is its registry id (SKILL.md § Artifacts); the referee has none.</summary>
    public static string StudyFolder(string studyId) => studyId;

    /// <summary>
    /// The promoted, declined and pending counts over a generated candidates.md (d-2026-09-10-9),
    /// read from the status the view materialises per diagnostic candidate — promoted where a
    /// hypothesis record cites it, declined from declined-candidates.md, else pending
    /// (d-2026-09-10-7). Non-diagnostic claims carry no status and are not counted.
    /// </summary>
    static string CandidateCounts(string file)
    {
        int promoted = 0, declined = 0, pending = 0;
        foreach (var raw in File.ReadAllText(file).Replace("\r\n", "\n").Split('\n'))
        {
            var l = raw.Trim();
            if (l == "- status: promoted") promoted++;
            else if (l == "- status: declined") declined++;
            else if (l == "- status: pending") pending++;
        }
        return $"{promoted} promoted, {declined} declined, {pending} pending";
    }

    // ---- files on disk matching an artifact's pattern ----

    public static IReadOnlyList<string> Matches(string repoRoot, ArtifactPath path, string? studyFolder, string? corpus)
    {
        if (path.NoSinglePattern) return [];
        var prefix = path.FixedPrefix(studyFolder, corpus);
        var dir = prefix.Length == 0 ? repoRoot : Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar));
        if (!Directory.Exists(dir)) return [];

        var regex = path.ToRegex(studyFolder, corpus);
        var entries = path.IsDirectory
            ? Directory.GetDirectories(dir, "*", SearchOption.AllDirectories)
                .Where(d => Directory.EnumerateFiles(d, "*", SearchOption.AllDirectories).Any())
            : Directory.GetFiles(dir, "*", SearchOption.AllDirectories);

        return entries
            .Where(e => regex.IsMatch(Path.GetRelativePath(repoRoot, e).Replace('\\', '/')))
            .OrderBy(e => e, StringComparer.Ordinal)
            .ToList();
    }

    static int CountMatches(string repoRoot, ArtifactPath path, string? studyFolder, string? corpus)
        => Matches(repoRoot, path, studyFolder, corpus).Count;

    // ---- corpora ----

    static IReadOnlyList<Question> ReadQuestions(string repoRoot, SkillDocument doc, out string? note)
    {
        note = null;
        var row = doc.Artifact(WellKnown.QuestionList);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _))
        {
            note = $"No `{WellKnown.QuestionList}` artifact row with a parseable path; the lists cannot be located.";
            return [];
        }
        var prefix = path!.FixedPrefix();
        if (!Directory.Exists(Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar))))
        {
            note = $"Question lists absent: `{prefix}/` does not exist.";
            return [];
        }

        var questions = new List<Question>();
        foreach (var file in Matches(repoRoot, path, null, null))
        {
            var corpus = Path.GetFileNameWithoutExtension(file);
            questions.AddRange(ParseQuestions(corpus, File.ReadAllText(file)));
        }
        if (questions.Count == 0) note = $"Question lists under `{prefix}/` hold no entries.";
        return questions;
    }

    public static IReadOnlyList<Question> ParseQuestions(string corpus, string text)
    {
        var result = new List<Question>();
        string? slug = null;
        var withdrawn = false;

        void Flush()
        {
            if (slug is not null) result.Add(new Question(corpus, slug, withdrawn));
            slug = null; withdrawn = false;
        }

        foreach (var raw in text.Replace("\r\n", "\n").Split('\n'))
        {
            var line = raw.Trim();
            if (line.StartsWith("### ", StringComparison.Ordinal))
            {
                Flush();
                var heading = line[4..].Trim(); // "<corpus>/<slug>", the citation token (d-2026-09-07-31)
                slug = heading[(heading.IndexOf('/') + 1)..];
                continue;
            }
            if (line.StartsWith("## ", StringComparison.Ordinal) || line.StartsWith("# ", StringComparison.Ordinal)) { Flush(); continue; }
            if (slug is null) continue;
            if (line.StartsWith("- withdrawn:", StringComparison.Ordinal)) withdrawn = true;
            else if (line.StartsWith("- reinstated:", StringComparison.Ordinal)) withdrawn = false;
        }
        Flush();
        return result;
    }

    static void Corpora(StringBuilder sb, string repoRoot, SkillDocument doc, IReadOnlyList<Question> questions, string? note)
    {
        sb.Append("## Corpora\n\n");
        if (note is not null) { sb.Append(note).Append("\n\n"); if (questions.Count == 0) return; }

        var versions = ReadDirections(repoRoot, doc);
        var verifications = ReadVerifications(repoRoot, doc);

        foreach (var corpus in questions.Select(q => q.Corpus).Distinct(StringComparer.Ordinal).OrderBy(c => c, StringComparer.Ordinal))
        {
            var mine = questions.Where(q => q.Corpus == corpus).ToList();
            var open = mine.Where(q => q.IsOpen).ToList();
            sb.Append($"### {corpus}\n\n");
            sb.Append($"{open.Count} open, {mine.Count - open.Count} withdrawn.\n\n");
            if (open.Count == 0) continue;
            sb.Append("| question | covered by (calibrated directions) | answered by (verification) |\n|---|---|---|\n");
            foreach (var q in open)
            {
                var covering = versions.Where(c => c.Calibrated && c.Questions.Contains(q.Cite, StringComparer.Ordinal)).Select(c => c.Cite).ToList();
                var answering = verifications.Where(v => v.Questions.Contains(q.Cite, StringComparer.Ordinal)).Select(v => v.Study).ToList();
                sb.Append("| ").Append(q.Slug)
                  .Append(" | ").Append(covering.Count == 0 ? "nothing" : string.Join(" ", covering))
                  .Append(" | ").Append(answering.Count == 0 ? "nothing" : string.Join(" ", answering))
                  .Append(" |\n");
            }
            sb.Append('\n');
        }
    }

    /// <summary>
    /// Every directions version the table locates, with its body hash and the questions its
    /// frontmatter names; calibrated when a calibration file beside it, or one a definition
    /// names, is titled with its hash and accepts it.
    /// </summary>
    public static IReadOnlyList<DirectionsVersion> ReadDirections(string repoRoot, SkillDocument doc)
    {
        var row = doc.Artifact(WellKnown.Directions);
        var calRow = doc.Artifact(WellKnown.Calibration);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _)) return [];

        var accepted = new HashSet<string>(StringComparer.Ordinal); // hashes (possibly prefixes) with an accepting calibration
        if (calRow is not null && ArtifactPath.TryParse(calRow.Path, out var calPath, out _))
            foreach (var file in Matches(repoRoot, calPath!, null, null))
            {
                var cal = CalibrationFile.Read(file);
                if (cal.TitleParsed && cal.Accepted) accepted.Add(cal.Hash!);
            }
        // The referee's calibrations, reached only by reference from definitions.
        if (doc.Artifact(WellKnown.Definition) is { } defRow && ArtifactPath.TryParse(defRow.Path, out var defPath, out _))
            foreach (var file in Matches(repoRoot, defPath!, null, null))
            {
                DefinitionFile d;
                try { d = DefinitionFile.Read(file); } catch (IOException) { continue; }
                if (d.CalibrationPath is not null && File.Exists(d.CalibrationPath))
                {
                    var cal = CalibrationFile.Read(d.CalibrationPath);
                    if (cal.TitleParsed && cal.Accepted) accepted.Add(cal.Hash!);
                }
            }

        var files = Matches(repoRoot, path!, null, null).ToList();
        var referee = Path.Combine(repoRoot, "docs", "v3-framework", "referee");
        if (Directory.Exists(referee)) files.AddRange(Directory.GetFiles(referee, "directions-*.md").OrderBy(f => f, StringComparer.Ordinal));

        var result = new List<DirectionsVersion>();
        foreach (var file in files.Distinct(StringComparer.OrdinalIgnoreCase))
        {
            var d = DirectionsFile.Read(file);
            var calibrated = accepted.Any(h => Hashing.Cites(h, d.BodyHash));
            result.Add(new DirectionsVersion(Path.GetRelativePath(repoRoot, file).Replace('\\', '/'), d.BodyHash, d.Questions, calibrated));
        }
        return result;
    }

    sealed record Verification(string Study, IReadOnlyList<string> Questions);

    /// <summary>A question is answered when a standing finding names it (d-2026-09-09-16): read from every findings file the table locates.</summary>
    static IReadOnlyList<Verification> ReadVerifications(string repoRoot, SkillDocument doc)
    {
        var row = doc.Artifact(WellKnown.Findings);
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _)) return [];
        var result = new List<Verification>();
        foreach (var file in Matches(repoRoot, path!, null, null))
        {
            var questions = FindingsChecker.AnsweredQuestions(File.ReadAllText(file));
            var study = Path.GetFileName(Path.GetDirectoryName(file)!)!;
            result.Add(new Verification(study, questions));
        }
        return result;
    }

    /// <summary>The body under a <c>## heading</c>, up to the next heading of any level.</summary>
    public static string Section(string text, string heading)
    {
        var lines = text.Replace("\r\n", "\n").Split('\n');
        var sb = new StringBuilder();
        var inside = false;
        var inFence = false;
        foreach (var line in lines)
        {
            var t = line.Trim();
            if (t.StartsWith("```", StringComparison.Ordinal)) { inFence = !inFence; if (inside) sb.Append(line).Append('\n'); continue; }
            if (!inFence && t.StartsWith('#'))
            {
                if (inside) break;
                inside = t.TrimStart('#').Trim().Equals(heading, StringComparison.Ordinal);
                continue;
            }
            if (inside) sb.Append(line).Append('\n');
        }
        return sb.ToString();
    }

    // ---- hypotheses ----

    static void Hypotheses(StringBuilder sb, string repoRoot, SkillDocument doc)
    {
        sb.Append("## Hypotheses\n\n");
        var row = doc.Artifact(WellKnown.HypothesisRecord) ?? doc.Artifacts.FirstOrDefault(a => WellKnown.HypothesisArtifacts.Contains(a.Id));
        if (row is null || !ArtifactPath.TryParse(row.Path, out var path, out _))
        {
            sb.Append("No hypothesis artifact row with a parseable path; the files cannot be located.\n\n");
            return;
        }
        var prefix = path!.FixedPrefix();
        if (!Directory.Exists(Path.Combine(repoRoot, prefix.Replace('/', Path.DirectorySeparatorChar))))
        {
            sb.Append($"Hypothesis files absent: `{prefix}/` does not exist.\n\n");
            return;
        }

        var files = Matches(repoRoot, path, null, null);
        if (files.Count == 0) { sb.Append($"No hypothesis files under `{prefix}/`.\n\n"); return; }

        sb.Append("Nothing here is authored: status and baselined are read from the entries below the last " +
                  "`### iteration`, which is the wording boundary — a challenging entry → challenged, else an " +
                  "evidence entry → evidenced, else untested; whether a challenge is resolved is not derived " +
                  "(d-2026-09-11-12).\n\n");
        sb.Append("| id | slug | status | baselined |\n|---|---|---|---|\n");
        foreach (var file in files)
        {
            var h = ParseHypothesis(file);
            if (h is null) continue;
            sb.Append("| ").Append(h.Id.ToString("000"))
              .Append(" | ").Append(h.Slug)
              .Append(" | ").Append(h.Status)
              .Append(" | ").Append(h.Baselined)
              .Append(" |\n");
        }
        sb.Append('\n');
    }

    /// <summary>
    /// One hypothesis as state.md shows it. Since d-2026-09-11-12 the file authors nothing
    /// derivable: the id is its file name, and status and baselined are read from the entries
    /// below the last iteration boundary.
    /// </summary>
    public static Hypothesis? ParseHypothesis(string file)
    {
        var name = Path.GetFileNameWithoutExtension(file);
        var dash = name.IndexOf('-');
        if (dash < 3 || !int.TryParse(name[..dash], out var id)) return null;
        var slug = name[(dash + 1)..];

        var text = File.ReadAllText(file).Replace("\r\n", "\n");
        var entries = new List<(string Kind, string Body)>();
        string? kind = null;
        var body = new List<string>();
        foreach (var line in RecordSection(text))
        {
            if (line.StartsWith("### ", StringComparison.Ordinal))
            {
                if (kind is not null) entries.Add((kind, string.Join('\n', body)));
                kind = line[4..].Trim();
                body = [];
                continue;
            }
            if (kind is not null) body.Add(line);
        }
        if (kind is not null) entries.Add((kind, string.Join('\n', body)));

        var lastIteration = entries.FindLastIndex(e => e.Kind == "iteration");
        var current = entries.Skip(lastIteration + 1).ToList();
        var evidence = current.Where(e => e.Kind == "evidence").ToList();
        var status = evidence.Any(e => e.Body.Contains("- tag: challenging", StringComparison.Ordinal)) ? "challenged"
            : evidence.Count > 0 ? "evidenced"
            : "untested";
        var baselined = current.LastOrDefault(e => e.Kind == "baselined").Body is { } b
            ? Keyed(b, "date") ?? "yes"
            : "false";

        return new Hypothesis(id, slug, status, baselined, status);
    }

    /// <summary>
    /// The lines of § Record. Not <see cref="Section"/>: that stops at the next line beginning
    /// `##`, and the record's entries are `### <kind>` headings, which begin that way too.
    /// </summary>
    static IEnumerable<string> RecordSection(string text)
    {
        var inside = false;
        foreach (var line in text.Split('\n'))
        {
            if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                if (inside) yield break;
                inside = line.Trim() == "## Record";
                continue;
            }
            if (inside) yield return line;
        }
    }

    /// <summary>The value of one `- key: value` line of an entry body, or null.</summary>
    static string? Keyed(string body, string key)
        => body.Split('\n')
            .Select(l => l.TrimEnd())
            .FirstOrDefault(l => l.StartsWith($"- {key}: ", StringComparison.Ordinal))?[(key.Length + 4)..];
}
