using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using GongSolutions.Wpf.DragDrop;
using StoryPlanner.Core;
using StoryPlanner.Core.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;
using System.Windows;
using System.Windows.Input;

namespace WindowedStoryPlanner.ViewModels
{
    public partial class OwnerViewModel : ObservableObject, IDropTarget
    {
        IStoryService _storyService;
        IViewModelRegistry _viewModelRegistry;
        public ObservableCollection<NoteTrackViewModel> NoteTracks { get; set; } = new ObservableCollection<NoteTrackViewModel>();
        public ObservableCollection<NarrativePropertyViewModel> NarrativeProperties { get; set; } = new ObservableCollection<NarrativePropertyViewModel>();
        public OwnerViewModel(IViewModelRegistry viewModelRegistry, IStoryService storyService)
        {
            _storyService = storyService;
            _viewModelRegistry = viewModelRegistry;
        }

        protected void InitializeCollections(
            int ownerId,
            OwnerType ownerType,
            List<NoteTrackDefinition> noteTrackDefinitions,
            List<NarrativePropertyDefinition> narrativePropertyDefinitions)
        {
            foreach (var ntd in noteTrackDefinitions)
            {
                var trackVm = new NoteTrackViewModel(
                    ntd,
                    ownerId,      // passed through so NoteTrackViewModel 
                    ownerType,    // can filter notes correctly
                    _viewModelRegistry,
                    _storyService);
                NoteTracks.Add(trackVm);
            }

            //TODO: add another NoteTrackViewModel to NoteTracks for unset when the criteria don't match

            foreach (var npd in narrativePropertyDefinitions)
            {
                var propVm = new NarrativePropertyViewModel(
                    ownerId,
                    ownerType,
                    npd,
                    _viewModelRegistry,
                    _storyService);
                NarrativeProperties.Add(propVm);
            }
        }

        public virtual void DragOver(IDropInfo dropInfo)
        {
            object source = dropInfo.Data;
            var target = this;

            PlotPointViewModel? plotPoint = source as PlotPointViewModel ?? target as PlotPointViewModel;
            SubjectViewModel? otherEntity = (source == plotPoint) ? target as SubjectViewModel : source as SubjectViewModel;

            bool isTypeCompatible = (source, target) switch
            {
                (SubjectViewModel, PlotPointViewModel) => true,
                (PlotPointViewModel, SubjectViewModel) => true,
                (PlotPointSubjectLinkViewModel, PlotPointViewModel) => true,
                (PlotPointSubjectLinkViewModel, SubjectViewModel s) => true,
                _ => false
            };

            if (isTypeCompatible && plotPoint != null && otherEntity != null && !LinkExists(plotPoint, otherEntity))
            {
                dropInfo.DropTargetAdorner = DropTargetAdorners.Highlight;
                dropInfo.Effects = DragDropEffects.Move;
            }
            else
            {
                dropInfo.Effects = DragDropEffects.None;
            }
        }

        public async virtual void Drop(IDropInfo dropInfo)
        {
            var source = dropInfo.Data;
            var target = this;

            switch (source, target)
            {
                case (SubjectViewModel s, PlotPointViewModel p): await CreateNewLink(p, s); break;
                case (PlotPointViewModel p, SubjectViewModel s): await CreateNewLink(p, s); break;
                case (PlotPointSubjectLinkViewModel l, PlotPointViewModel p): MoveLinkToNewPlotPoint(l, p); break;
                case (PlotPointSubjectLinkViewModel l, SubjectViewModel s): MoveLinkToNewSubject(l, s); break;
            }
        }

        private async Task CreateNewLink(PlotPointViewModel p, SubjectViewModel s)
        {
            if (LinkExists(p, s))
                return;
            var l = new PlotPointSubjectLink()
            {
                PlotPointId = p.Id,
                SubjectId = s.Id
            };
            _storyService.PlotPointsSubjectLinks.Add(l);
            await _storyService.SaveAsync(); //saving will populate the link instance with the autogenerated Id

            _viewModelRegistry.AllPlotPointSubjectLinkViewModels.Add(new PlotPointSubjectLinkViewModel(l, _viewModelRegistry, _storyService));

        }

        private bool LinkExists(PlotPointViewModel p, SubjectViewModel s)
        {
            return _viewModelRegistry.AllPlotPointSubjectLinkViewModels.Any(l => l.PlotPointId == p.Id && l.SubjectId == s.Id);
        }

        private void MoveLinkToNewPlotPoint(PlotPointSubjectLinkViewModel l, PlotPointViewModel p)
        {
            l.PlotPointId = p.Id;
        }

        private void MoveLinkToNewSubject(PlotPointSubjectLinkViewModel l, SubjectViewModel s)
        {
            l.SubjectId = s.Id;
        }

        private void RegisterTrackHotkeys(
    IEnumerable<NoteTrackDefinition> noteTrackDefinitions)
        {
            foreach (var noteTrackDefinition in noteTrackDefinitions
                .Where(c => c.FunctionKeyNumber.HasValue))
            {
                var key = KeyFromFunctionNumber(
                    noteTrackDefinition.FunctionKeyNumber!.Value);

                var binding = new KeyBinding(
                    new RelayCommand(() =>
                        MoveSelectedNoteToTrack(noteTrackDefinition.Id)),
                    key,
                    ModifierKeys.None);

                //InputBindings.Add(binding);
            }
        }

        private void MoveSelectedNoteToTrack(int noteTrackDefinitionId)
        {
            
        }

        private static Key KeyFromFunctionNumber(int n) => n switch
        {
            1 => Key.F1,
            2 => Key.F2,
            3 => Key.F3,
            4 => Key.F4,
            5 => Key.F5,
            6 => Key.F6,
            7 => Key.F7,
            8 => Key.F8,
            9 => Key.F9,
            10 => Key.F10,
            11 => Key.F11,
            12 => Key.F12,
            _ => throw new ArgumentOutOfRangeException(nameof(n))
        };
    }
}
