using System.Collections.Concurrent;
using StoryPlanner.AgentRunner;

namespace StoryPlanner.Tests;

/// <summary>
/// A child launcher that starts no process: it writes the job's output (unless told not to),
/// writes a one-line stream, holds for as long as the test says, and can be "killed". Lets the
/// batch loop's queue, ceilings, pause, stop and cancel semantics be tested in the pure tier.
/// </summary>
public sealed class FakeLauncher : IChildLauncher
{
    private sealed class Handle(TaskCompletionSource<int> killed) : IChildHandle
    {
        public int Pid => 4242;
        public void Kill() => killed.TrySetResult(137);
    }

    private int _current;
    public int MaxConcurrent;
    public int Launched;
    public readonly ConcurrentQueue<string> Order = new();
    /// <summary>When set, a launch waits here (one release per launch) instead of the fixed delay.</summary>
    public SemaphoreSlim? Hold;
    public TimeSpan Delay = TimeSpan.FromMilliseconds(30);
    public Func<ChildRequest, int> ExitFor = _ => 0;
    public Func<ChildRequest, bool> WriteOutput = _ => true;

    public async Task<int> LaunchAsync(ChildRequest request, Action<IChildHandle> track, Action onStreamAdvanced, CancellationToken ct)
    {
        var now = Interlocked.Increment(ref _current);
        Interlocked.Increment(ref Launched);
        Order.Enqueue(request.Job.Id);
        lock (this) MaxConcurrent = Math.Max(MaxConcurrent, now);
        var killed = new TaskCompletionSource<int>(TaskCreationOptions.RunContinuationsAsynchronously);
        track(new Handle(killed));
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(request.StreamPath)!);
            await File.WriteAllTextAsync(request.StreamPath,
                """{"type":"system","subtype":"init","tools":["Write"],"mcp_servers":[],"model":"fake"}""" + "\n", ct);
            onStreamAdvanced();

            var wait = Hold is not null ? Hold.WaitAsync(ct) : Task.Delay(Delay, ct);
            var done = await Task.WhenAny(wait, killed.Task);
            if (done == killed.Task) return 137;
            await wait;

            if (WriteOutput(request))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(request.Job.OutputPath)!);
                await File.WriteAllTextAsync(request.Job.OutputPath, "## " + request.Job.Id + "\nok\n", ct);
            }
            await File.AppendAllTextAsync(request.StreamPath,
                """{"type":"result","total_cost_usd":0.01,"num_turns":1,"session_id":"s","result":"done"}""" + "\n", ct);
            onStreamAdvanced();
            return ExitFor(request);
        }
        finally
        {
            Interlocked.Decrement(ref _current);
        }
    }
}

/// <summary>A throwaway run folder and launch folder under the temp dir, with a job file of N inline jobs.</summary>
public sealed class TempRun : IDisposable
{
    public string Root { get; }
    public string FanoutRoot { get; }
    public string RunDir { get; }
    public string LaunchDir { get; }
    public string JobFilePath => Path.Combine(RunDir, "jobs.json");

    public TempRun(string work = "work", string run = "run-1")
    {
        Root = Path.Combine(Path.GetTempPath(), "sp-runner-" + Guid.NewGuid().ToString("N"));
        FanoutRoot = Path.Combine(Root, "fanout");
        RunDir = Path.Combine(FanoutRoot, work, run);
        LaunchDir = Path.Combine(Root, "launch");
        Directory.CreateDirectory(RunDir);
        Directory.CreateDirectory(LaunchDir);
    }

    public string WriteJobs(int count, int maxParallel = 1, int maxAttempts = 1, string? extraJson = null)
    {
        var jobs = string.Join(",\n", Enumerable.Range(1, count).Select(i =>
            $$"""{ "id": "job-{{i:00}}", "item": "item {{i}}", "instructions": "go", "outputPath": "results/job-{{i:00}}.md", "requireOnce": ["## job-{{i:00}}"] }"""));
        var json = $$"""
            {
              "_comment": ["Generated by test"],
              "launchDir": {{System.Text.Json.JsonSerializer.Serialize(LaunchDir)}},
              "maxAttempts": {{maxAttempts}}, "maxParallel": {{maxParallel}}, "timeoutMinutes": 1, "utilizationCap": 100,
              "defaults": { "model": "sonnet", "tools": ["Write"], "mcp": false }{{(extraJson is null ? "" : "," + extraJson)}},
              "jobs": [ {{jobs}} ]
            }
            """;
        File.WriteAllText(JobFilePath, json);
        return JobFilePath;
    }

    public void Dispose()
    {
        try { Directory.Delete(Root, recursive: true); } catch { }
    }
}

public static class Wait
{
    public static async Task Until(Func<bool> condition, int timeoutMs = 5000, string? what = null)
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        while (!condition())
        {
            if (DateTime.UtcNow > deadline) throw new TimeoutException("waited for: " + (what ?? "condition"));
            await Task.Delay(20);
        }
    }
}
