using StoryPlanner.AgentRunner;
using Xunit;

namespace StoryPlanner.Tests;

/// <summary>
/// The history view and the stage strip are read from a run folder on disk: run id from the
/// path, job states from the ledger, stages from what files exist. A run whose job file no
/// longer parses is still listed from its ledger. Tier: pure (temp folders).
/// </summary>
public class RunCatalogTests
{
    private static LedgerRow Row(string job, int exit, bool output, string check, string? mode = null, string end = "2026-09-03T20:00:00+00:00") =>
        new(job, 1, "sonnet", "2.1", "abc", [], [], "2026-09-03T19:59:00+00:00", end, exit, "attempts/" + job + "/attempt-1/stream.jsonl", output, 0.2, 2, "s", check, mode);

    [Fact]
    public void Reads_a_finished_run_from_disk_with_its_stages()
    {
        using var t = new TempRun(work: "skill-audits", run: "2026-09-03-doc");
        t.WriteJobs(2);
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"),
            [RunnerPlan.SerializeLedgerRow(Row("job-01", 0, true, "ok", mode: "pilot")), RunnerPlan.SerializeLedgerRow(Row("job-02", 0, true, "ok"))]);
        Directory.CreateDirectory(Path.Combine(t.RunDir, "items"));
        File.WriteAllText(Path.Combine(t.RunDir, "items", "manifest.md"), "# Units");
        File.WriteAllText(Path.Combine(t.RunDir, "run.md"), "# The run\n\nOne arm only.");
        var work = Path.GetDirectoryName(t.RunDir)!;
        File.WriteAllText(Path.Combine(work, "protocol.md"), "# Protocol");
        File.WriteAllText(Path.Combine(work, "tally.ps1"), "# tally");

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);

        Assert.Equal("skill-audits/2026-09-03-doc", snap.RunId);
        Assert.Equal("skill-audits", snap.Work);
        Assert.False(snap.Live);
        Assert.True(snap.Completed);
        Assert.Equal(2, snap.Succeeded);
        Assert.Equal(0.4, snap.CostUsd, 3);
        Assert.True(snap.InputsResolvable);
        Assert.Contains("One arm only", snap.RunMd);
        Assert.Equal("Succeeded", snap.Jobs[0].State);
        Assert.Equal("item 1", snap.Jobs[0].Item);
        Assert.Equal(60, snap.Jobs[0].LastSeconds);

        var s = snap.Stages;
        Assert.True(s.Instrument);
        Assert.Null(s.Calibrated);            // a protocol, not a codebook
        Assert.True(s.Enumerated);
        Assert.True(s.Generated);             // "Generated by" in jobs.json
        Assert.True(s.Piloted);
        Assert.True(s.BatchComplete);
        Assert.True(s.Tallied);
        Assert.True(s.Documented);
    }

    [Fact]
    public void A_codebook_work_reports_calibration_separately_and_a_pending_run_is_not_complete()
    {
        using var t = new TempRun(work: "referee", run: "2026-09-10-wu2-3");
        t.WriteJobs(2);
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"), [RunnerPlan.SerializeLedgerRow(Row("job-01", 0, true, "ok"))]);
        var work = Path.GetDirectoryName(t.RunDir)!;
        File.WriteAllText(Path.Combine(work, "codebook.md"), "# Codebook");

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);
        Assert.True(snap.Stages.Instrument);
        Assert.False(snap.Stages.Calibrated);
        Assert.False(snap.Stages.BatchComplete);
        Assert.Equal(1, snap.Pending);

        File.WriteAllText(Path.Combine(work, "calibration-2026-09-10.md"), "# Calibration");
        Assert.True(RunCatalog.Load(t.RunDir, t.FanoutRoot).Stages.Calibrated);
    }

    [Fact]
    public void An_unparsable_job_file_still_lists_the_run_from_its_ledger()
    {
        using var t = new TempRun();
        File.WriteAllText(t.JobFilePath, "{ not json");
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"),
            [RunnerPlan.SerializeLedgerRow(Row("old-01", 0, true, "ok")), RunnerPlan.SerializeLedgerRow(Row("old-02", 1, false, "no output file"))]);

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);
        Assert.NotNull(snap.Error);
        Assert.False(snap.InputsResolvable);
        Assert.Equal(2, snap.Jobs.Count);
        Assert.Equal("Succeeded", snap.Jobs[0].State);
        Assert.Equal("Failed", snap.Jobs[1].State);
        Assert.Equal("(job file not readable)", snap.Jobs[0].Item);
    }

    [Fact]
    public void Run_dirs_are_every_ledger_under_the_root_and_ids_use_forward_slashes()
    {
        using var t = new TempRun(work: "a", run: "r1");
        File.WriteAllText(Path.Combine(t.RunDir, "ledger.jsonl"), "");
        var other = Path.Combine(t.FanoutRoot, "b");
        Directory.CreateDirectory(other);
        File.WriteAllText(Path.Combine(other, "ledger.jsonl"), "");

        var ids = RunCatalog.RunDirs(t.FanoutRoot).Select(d => RunCatalog.RunIdFor(d, t.FanoutRoot)).OrderBy(x => x).ToList();
        Assert.Equal(["a/r1", "b"], ids);
    }
}
