using StoryPlanner.AgentRunner;
using Xunit;

namespace StoryPlanner.Tests;

/// <summary>
/// The history view and the stage strip are read from a run folder on disk: run id from the
/// path, job states from the ledger, stages from what files exist. A run whose job file no
/// longer parses is still listed from its ledger. Tier: pure (temp folders).
/// </summary>
public class RunCatalogTests
{
    private static LedgerRow Row(string job, int exit, bool output, string check, string? mode = null, string end = "2026-09-03T20:00:00+00:00") =>
        new(job, 1, "sonnet", "2.1", "abc", [], [], "2026-09-03T19:59:00+00:00", end, exit, "attempts/" + job + "/attempt-1/stream.jsonl", output, 0.2, 2, "s", check, mode);

    [Fact]
    public void Reads_a_finished_run_from_disk_with_its_stages()
    {
        using var t = new TempRun(work: "skill-audits", run: "2026-09-03-doc");
        t.WriteJobs(2);
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"),
            [RunnerPlan.SerializeLedgerRow(Row("job-01", 0, true, "ok", mode: "pilot")), RunnerPlan.SerializeLedgerRow(Row("job-02", 0, true, "ok"))]);
        Directory.CreateDirectory(Path.Combine(t.RunDir, "items"));
        File.WriteAllText(Path.Combine(t.RunDir, "items", "manifest.md"), "# Units");
        File.WriteAllText(Path.Combine(t.RunDir, "run.md"), "# The run\n\nOne arm only.");
        var work = Path.GetDirectoryName(t.RunDir)!;
        File.WriteAllText(Path.Combine(work, "protocol.md"), "# Protocol");
        File.WriteAllText(Path.Combine(work, "tally.ps1"), "# tally");

        // The tallier being present is not a tally having been produced (2026-09-05).
        Assert.False(RunCatalog.Load(t.RunDir, t.FanoutRoot).Stages.Tallied);
        File.WriteAllText(Path.Combine(t.RunDir, "tally.md"), "# tally.md");

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);

        Assert.Equal("skill-audits/2026-09-03-doc", snap.RunId);
        Assert.Equal("skill-audits", snap.Work);
        Assert.False(snap.Live);
        Assert.True(snap.Completed);
        Assert.Equal(2, snap.Succeeded);
        Assert.Equal(0.4, snap.CostUsd, 3);
        Assert.True(snap.InputsResolvable);
        Assert.Contains("One arm only", snap.RunMd);
        Assert.Equal("Succeeded", snap.Jobs[0].State);
        Assert.Equal("item 1", snap.Jobs[0].Item);
        Assert.Equal(60, snap.Jobs[0].LastSeconds);

        var s = snap.Stages;
        Assert.True(s.Instrument);
        Assert.Null(s.Calibrated);            // a protocol, not a codebook
        Assert.True(s.Enumerated);
        Assert.True(s.Generated);             // "Generated by" in jobs.json
        Assert.True(s.Piloted);
        Assert.True(s.BatchComplete);
        Assert.True(s.Tallied);
        Assert.True(s.Documented);
    }

    [Fact]
    public void A_codebook_work_reports_calibration_separately_and_a_pending_run_is_not_complete()
    {
        using var t = new TempRun(work: "referee", run: "2026-09-10-wu2-3");
        t.WriteJobs(2);
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"), [RunnerPlan.SerializeLedgerRow(Row("job-01", 0, true, "ok"))]);
        var work = Path.GetDirectoryName(t.RunDir)!;
        File.WriteAllText(Path.Combine(work, "codebook-2.md"), "# Codebook");   // versioned by number, as artifacts.md names it

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);
        Assert.True(snap.Stages.Instrument);
        Assert.False(snap.Stages.Calibrated);
        Assert.False(snap.Stages.BatchComplete);
        Assert.Equal(1, snap.Pending);

        File.WriteAllText(Path.Combine(work, "calibration-2026-09-10.md"), "# Calibration");
        Assert.True(RunCatalog.Load(t.RunDir, t.FanoutRoot).Stages.Calibrated);
    }

    /// <summary>
    /// The run is the job file, not the enqueued subset: after a pilot (<c>--job</c>) the other
    /// jobs are pending and the batch is not complete — read from disk, and read from the live
    /// runner that holds one job, which on 2026-09-05 reported "pending 0, batch complete" with
    /// 45 of 46 jobs never launched.
    /// </summary>
    [Fact]
    public async Task A_pilot_only_ledger_leaves_the_rest_of_the_file_pending_whether_read_from_disk_or_from_the_live_runner()
    {
        using var t = new TempRun(work: "skill-audits", run: "2026-09-05-audit");
        t.WriteJobs(3);
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"), [RunnerPlan.SerializeLedgerRow(Row("job-02", 0, true, "ok", mode: "pilot"))]);

        var disk = RunCatalog.Load(t.RunDir, t.FanoutRoot);
        Assert.Equal(3, disk.Jobs.Count);
        Assert.Equal(["Pending", "Succeeded", "Pending"], disk.Jobs.Select(j => j.State));
        Assert.Equal(2, disk.Pending);
        Assert.Equal(1, disk.Succeeded);
        Assert.False(disk.Completed);
        Assert.True(disk.Stages.Piloted);
        Assert.False(disk.Stages.BatchComplete);

        // The live runner under --job holds one job; the snapshot still describes the file.
        var (runner, error) = BatchRunner.Create(t.JobFilePath, disk.RunId, "job-02", new FakeLauncher(), new OpenGate(), _ => { }, "test");
        Assert.Null(error);
        Assert.Single(runner!.Jobs);
        var live = RunCatalog.Build(t.RunDir, t.FanoutRoot, runner);
        Assert.Equal(3, live.Jobs.Count);
        Assert.Equal(2, live.Pending);
        Assert.False(live.Completed);
        Assert.False(live.Stages.BatchComplete);

        // A second enqueue of the whole file says what it will do, from the ledger.
        var (batch, _) = BatchRunner.Create(t.JobFilePath, disk.RunId, null, new FakeLauncher(), new OpenGate(), _ => { }, "test");
        Assert.Equal("3 job(s) enqueued — 2 to launch, 1 skipped as succeeded, 0 already failed and not relaunched", RunnerHost.EnqueueTally(batch!));
        await batch!.RunAsync(CancellationToken.None);
        var after = RunCatalog.Build(t.RunDir, t.FanoutRoot, batch);
        Assert.True(after.Completed);
        Assert.True(after.Stages.BatchComplete);
        Assert.Equal(0, after.Pending);
    }

    [Fact]
    public void A_job_the_file_no_longer_names_is_still_listed_from_its_ledger_rows()
    {
        using var t = new TempRun();
        t.WriteJobs(2);
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"),
            [RunnerPlan.SerializeLedgerRow(Row("job-01", 0, true, "ok")), RunnerPlan.SerializeLedgerRow(Row("renamed-away", 1, false, "no output file"))]);

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);
        Assert.Equal(["job-01", "job-02", "renamed-away"], snap.Jobs.Select(j => j.Id));
        Assert.Equal("Failed", snap.Jobs[2].State);
        Assert.Equal("(job file not readable)", snap.Jobs[2].Item);
        Assert.Equal(1, snap.Pending);
        Assert.False(snap.Completed);
    }

    [Fact]
    public void An_unparsable_job_file_still_lists_the_run_from_its_ledger()
    {
        using var t = new TempRun();
        File.WriteAllText(t.JobFilePath, "{ not json");
        File.WriteAllLines(Path.Combine(t.RunDir, "ledger.jsonl"),
            [RunnerPlan.SerializeLedgerRow(Row("old-01", 0, true, "ok")), RunnerPlan.SerializeLedgerRow(Row("old-02", 1, false, "no output file"))]);

        var snap = RunCatalog.Load(t.RunDir, t.FanoutRoot);
        Assert.NotNull(snap.Error);
        Assert.False(snap.InputsResolvable);
        Assert.Equal(2, snap.Jobs.Count);
        Assert.Equal("Succeeded", snap.Jobs[0].State);
        Assert.Equal("Failed", snap.Jobs[1].State);
        Assert.Equal("(job file not readable)", snap.Jobs[0].Item);
    }

    [Fact]
    public void Run_dirs_are_every_ledger_under_the_root_and_ids_use_forward_slashes()
    {
        using var t = new TempRun(work: "a", run: "r1");
        File.WriteAllText(Path.Combine(t.RunDir, "ledger.jsonl"), "");
        var other = Path.Combine(t.FanoutRoot, "b");
        Directory.CreateDirectory(other);
        File.WriteAllText(Path.Combine(other, "ledger.jsonl"), "");

        var ids = RunCatalog.RunDirs(t.FanoutRoot).Select(d => RunCatalog.RunIdFor(d, t.FanoutRoot)).OrderBy(x => x).ToList();
        Assert.Equal(["a/r1", "b"], ids);
    }
}
