# Adds the unit range per file to <document>.files.md after the split verb has run: joins the
# file list make-document-a.ps1 wrote (line ranges in the document) with items\manifest.md
# (each unit's section heading) through the document itself (each heading's line number). The
# join is exact or refused: a heading that appears in two files cannot be assigned, and a
# file's units must be one contiguous range of the manifest. Nothing is guessed.
#
#   .\document-a-ranges.ps1 -Run .\2026-09-05-v3-buildout-2 [-Document document-a.md]
#
# Rewrites <document>.files.md whole with a units column; running it again is idempotent.
# ASCII only: Windows PowerShell 5.1 reads an unmarked file as ANSI.
param(
    [Parameter(Mandatory)] [string] $Run,
    [string] $Document = 'document-a.md'
)

$ErrorActionPreference = 'Stop'
$runPath = (Resolve-Path $Run).Path
$docPath = Join-Path $runPath $Document
$filesPath = [IO.Path]::ChangeExtension($docPath, '.files.md')
$manifestPath = Join-Path $runPath 'items\manifest.md'
foreach ($p in @($docPath, $filesPath, $manifestPath)) { if (-not (Test-Path $p)) { throw "no such file: $p" } }

# --- the file list: order, file, characters, first-last ---
$files = @()
foreach ($line in Get-Content $filesPath -Encoding UTF8) {
    if ($line -match '^\|\s*(\d+)\s*\|\s*(.*?)\s*\|\s*(\d+)\s*\|\s*(\d+)-(\d+)\s*\|') {
        $files += [pscustomobject]@{ Order = [int]$matches[1]; File = $matches[2]; Characters = [int]$matches[3]; FirstLine = [int]$matches[4]; LastLine = [int]$matches[5]; Units = @() }
    }
}
if ($files.Count -eq 0) { throw "$filesPath has no file rows" }

# --- the document's headings by line, outside fenced code ---
$docLines = [IO.File]::ReadAllText($docPath, [Text.Encoding]::UTF8) -split "`r?`n"
$headingFiles = @{}   # heading text -> set of file orders it appears in
$inFence = $false
for ($i = 0; $i -lt $docLines.Count; $i++) {
    $t = $docLines[$i]
    if ($t -match '^\s*```') { $inFence = -not $inFence; continue }
    if ($inFence) { continue }
    if ($t -match '^#{1,6}\s') {
        $heading = $t.Trim()
        $lineNo = $i + 1
        $owner = $files | Where-Object { $_.FirstLine -le $lineNo -and $lineNo -le $_.LastLine } | Select-Object -First 1
        if (-not $owner) { throw "heading at line $lineNo is outside every file's range: $heading" }
        if (-not $headingFiles.ContainsKey($heading)) { $headingFiles[$heading] = @{} }
        $headingFiles[$heading][$owner.Order] = $true
    }
}

# --- the manifest: unit -> section -> file ---
$units = @()
foreach ($line in Get-Content $manifestPath -Encoding UTF8) {
    if ($line -match '^\|\s*(unit-\d{3})\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|$') {
        $units += [pscustomobject]@{ Id = $matches[1]; Section = ($matches[2] -replace '\\\|', '|') }
    }
}
if ($units.Count -eq 0) { throw "$manifestPath has no unit rows" }

foreach ($u in $units) {
    if ($u.Section -eq '(frontmatter)') { $owner = $files[0] }
    else {
        if (-not $headingFiles.ContainsKey($u.Section)) { throw "$($u.Id): section '$($u.Section)' is not a heading of the document" }
        $owners = @($headingFiles[$u.Section].Keys)
        if ($owners.Count -ne 1) { throw "$($u.Id): heading '$($u.Section)' appears in files $($owners -join ', ') - the join cannot assign it" }
        $owner = $files | Where-Object { $_.Order -eq $owners[0] }
    }
    $owner.Units += $u.Id
}

# --- contiguity: a file's units are one range of the manifest ---
$ids = @($units | ForEach-Object { $_.Id })
foreach ($f in $files) {
    if ($f.Units.Count -eq 0) { continue }
    $firstIdx = $ids.IndexOf($f.Units[0]); $lastIdx = $ids.IndexOf($f.Units[-1])
    if ($lastIdx - $firstIdx + 1 -ne $f.Units.Count) { throw "$($f.File): its units are not one contiguous range of the manifest ($($f.Units[0])..$($f.Units[-1]) holds $($lastIdx - $firstIdx + 1), file has $($f.Units.Count))" }
}

# --- rewrite the file list with the units column, stamped with the document it joined against ---
# (the builder's stamp is the document it wrote; a checkout with other line endings hashes
# differently, and the run's manifest pins the bytes that were split, so this file names those)
$docText = [IO.File]::ReadAllText($docPath, [Text.Encoding]::UTF8)
$sha = (Get-FileHash $docPath -Algorithm SHA256).Hash.ToLowerInvariant()
$made = (Get-Content $filesPath -Encoding UTF8 | Where-Object { $_ -match 'generated by ../make-document-a.ps1 on (\d{4}-\d{2}-\d{2})' } | Select-Object -First 1)
$madeOn = if ($made -match 'on (\d{4}-\d{2}-\d{2})') { $matches[1] } else { '?' }
$out = New-Object System.Collections.Generic.List[string]
$out.Add("# Files of $([IO.Path]::GetFileName($docPath)) - generated by ../make-document-a.ps1 on $madeOn; units joined by ../document-a-ranges.ps1 on $(Get-Date -Format 'yyyy-MM-dd')")
$out.Add('')
$out.Add("Document sha256 $sha; $($files.Count) files, $($docText.Length) chars, $($units.Count) units. Line ranges and units are in the document as split (items/manifest.md pins the same bytes).")
$out.Add('')
$out.Add('| order | file | characters | lines | units |')
$out.Add('|---|---|---|---|---|')
foreach ($f in $files) {
    $range = if ($f.Units.Count -eq 0) { 'none' } else { "$($f.Units[0])..$($f.Units[-1]) ($($f.Units.Count))" }
    $out.Add("| $($f.Order) | $($f.File) | $($f.Characters) | $($f.FirstLine)-$($f.LastLine) | $range |")
}
[IO.File]::WriteAllText($filesPath, (($out -join "`n") + "`n"), (New-Object System.Text.UTF8Encoding($false)))
foreach ($f in $files) { Write-Host ("{0,-44} {1}" -f $f.File, $(if ($f.Units.Count -eq 0) { 'none' } else { "$($f.Units[0])..$($f.Units[-1]) ($($f.Units.Count))" })) }
Write-Host "-> $filesPath"
