# Generates a run's jobs.json from the manifest that the split verb wrote: one job per
# section of the old document, per arm, with the section's units as items and their ids as
# required markers. Batches are generated, never typed - the manifest is the source.
#
#   .\make-jobs.ps1 -Run .\2026-09-03-v3-buildout -DocA v3-buildout/SKILL.md `
#       -SetB @('../../../.claude/skills/v3-buildout2/SKILL.md', ...) -Arms @('arm-A','arm-B')
#
# Paths in -SetB are relative to the run folder (the runner resolves them there). Arms are
# identical runs under the same model; adjudicate the union of what either flags.
# ASCII only: Windows PowerShell 5.1 reads an unmarked file as ANSI.
param(
    [Parameter(Mandatory)] [string] $Run,
    [Parameter(Mandatory)] [string] $DocA,
    [Parameter(Mandatory)] [string[]] $SetB,
    [string[]] $Arms = @('arm-A', 'arm-B'),
    [string] $Model = 'sonnet',
    [int] $TimeoutMinutes = 15,
    [int] $MaxParallel = 4
)

$manifest = Join-Path $Run 'items\manifest.md'
if (-not (Test-Path $manifest)) { throw "no manifest at $manifest - run the split verb first" }

# Rows: | unit-001 | ## Section | first line |
$units = @()
foreach ($line in Get-Content $manifest -Encoding UTF8) {
    if ($line -match '^\|\s*(unit-\d{3})\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|$') {
        $units += [pscustomobject]@{ Id = $matches[1]; Section = $matches[2] }
    }
}
if ($units.Count -eq 0) { throw "manifest has no unit rows" }

# Group consecutive units by section, in document order.
$sections = @()
foreach ($u in $units) {
    if ($sections.Count -gt 0 -and $sections[-1].Section -eq $u.Section) { $sections[-1].Units += $u.Id }
    else { $sections += [pscustomobject]@{ Section = $u.Section; Units = @($u.Id) } }
}

function Slug([string] $s) {
    $t = ($s -replace '^#+\s*', '') -replace '[^A-Za-z0-9]+', '-'
    return $t.Trim('-').ToLowerInvariant()
}

$stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
$jobs = @()
foreach ($arm in $Arms) {
    $n = 0
    foreach ($sec in $sections) {
        $n++
        $slug = Slug $sec.Section
        if ($slug -eq '') { $slug = 'start' }
        $first = $sec.Units[0]; $last = $sec.Units[-1]
        $inputs = @($sec.Units | ForEach-Object { "items/$_.md" }) + $SetB
        $jobs += [ordered]@{
            id            = "$arm-$('{0:00}' -f $n)-$slug"
            item          = "$($sec.Units.Count) unit(s) $first..$last under '$($sec.Section)' of $DocA, against document set B"
            instructions  = "Apply the protocol to every unit input (the inputs named unit-NNN.md); every other input is a member of document set B. Write one block per unit to the output path."
            protocolFiles = @('../protocol.md')
            inputFiles    = $inputs
            outputPath    = "results/$arm-$slug.md"
            requireOnce   = @($sec.Units | ForEach-Object { "## $_" })
        }
    }
}

$file = [ordered]@{
    _comment = @(
        "Generated by ../make-jobs.ps1 from items/manifest.md on $stamp. Do not edit by hand; regenerate.",
        "One job per section per arm; document set B is every input after the unit files.",
        "Arms are identical runs under one model; adjudicate the union of what either flags."
    )
    launchDir      = 'C:\Users\Brian\RiderProjects\StoryPlanner-fanout'
    maxAttempts    = 1
    utilizationCap = 90
    timeoutMinutes = $TimeoutMinutes
    maxParallel    = $MaxParallel
    defaults       = [ordered]@{ model = $Model; permissionMode = 'auto'; tools = @('Write'); allowedTools = @('Write'); mcp = $false }
    jobs           = $jobs
}

$json = $file | ConvertTo-Json -Depth 6
# ConvertTo-Json in 5.1 escapes apostrophes and non-ASCII; keep the file readable.
$json = $json -replace '\\u0027', "'"
$json = [regex]::Replace($json, '\\u([0-9a-fA-F]{4})', { param($m) [string][char][Convert]::ToInt32($m.Groups[1].Value, 16) })
$target = Join-Path (Resolve-Path $Run) 'jobs.json'
[IO.File]::WriteAllText($target, $json + "`n", (New-Object System.Text.UTF8Encoding($false)))
Write-Host "$($jobs.Count) jobs ($($sections.Count) sections x $($Arms.Count) arm(s)) -> $target"
