# Tallies a supersession-audit run's results mechanically: relation counts, every unit whose
# relation is one of the flagged labels (with its section, quote and note), the counts per
# section of the old document in document order, and the malformed blocks. Adjudication reads
# the written tally.md, never the raw blocks.
#
#   .\tally.ps1 -Run .\2026-09-05-v3-buildout-2 [-Flag absent,reversed,delegated,narrowed] [-Out <path>]
#
# -Flag defaults to the method's omissions set (revising-the-method: narrowed, reversed, absent)
# plus delegated, a real relation of protocol.md. -Out defaults to <run>\tally.md, written UTF-8
# without BOM; the same text goes to stdout. Exit code 1 when any block is malformed: a relation
# outside the protocol's seven labels, an empty note on a relation other than restated, a unit id
# not in items\manifest.md, an id appearing twice across the result files, or a manifest unit with
# no block at all. Self-test: .\tally.test.ps1.
# ASCII only: Windows PowerShell 5.1 reads an unmarked file as ANSI.
param(
    [Parameter(Mandatory)] [string] $Run,
    [string[]] $Flag = @('absent', 'reversed', 'delegated', 'narrowed'),
    [string] $Out = ''
)

$ErrorActionPreference = 'Stop'
$runPath = (Resolve-Path $Run).Path
if ($Out -eq '') { $Out = Join-Path $runPath 'tally.md' }
$labels = @('restated', 'narrowed', 'broadened', 'reversed', 'delegated', 'absent', 'non-instructional')

$files = Get-ChildItem (Join-Path $runPath 'results') -Filter *.md | Sort-Object Name
if ($files.Count -eq 0) { throw "no results under $runPath" }

# --- the manifest: unit order and sections, as the split verb wrote them ---
$manifestPath = Join-Path $runPath 'items\manifest.md'
$manifestUnits = @()
if (Test-Path $manifestPath) {
    foreach ($line in Get-Content $manifestPath -Encoding UTF8) {
        if ($line -match '^\|\s*(unit-\d{3})\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|$') {
            $manifestUnits += [pscustomobject]@{ Id = $matches[1]; Section = ($matches[2] -replace '\\\|', '|') }
        }
    }
}

# --- the blocks ---
$blocks = @()
foreach ($f in $files) {
    $cur = $null
    foreach ($line in Get-Content $f.FullName -Encoding UTF8) {
        if ($line -match '^## (unit-\d{3})$') {
            if ($cur) { $blocks += $cur }
            $cur = [ordered]@{ Unit = $matches[1]; File = $f.Name; Section = ''; Quote = ''; Counterpart = ''; Relation = ''; Note = '' }
        }
        elseif ($cur -and $line -match '^- (section|quote|counterpart|relation|note):\s*(.*)$') {
            $key = (Get-Culture).TextInfo.ToTitleCase($matches[1])
            $cur[$key] = $matches[2]
        }
    }
    if ($cur) { $blocks += $cur }
}

# --- malformed: what the protocol's form does not admit ---
$malformed = @()
$seen = @{}
$manifestIds = @{}
foreach ($u in $manifestUnits) { $manifestIds[$u.Id] = $true }
foreach ($b in $blocks) {
    if ($labels -notcontains $b.Relation) {
        $malformed += "$($b.Unit) | $($b.File) | relation '$($b.Relation)' is not one of: $($labels -join ', ')"
    }
    $noteEmpty = ($b.Note.Trim() -eq '') -or ($b.Note.Trim() -match '^[-–—]$')
    if ($b.Relation -ne 'restated' -and $noteEmpty) {
        $malformed += "$($b.Unit) | $($b.File) | empty note on relation '$($b.Relation)'"
    }
    if ($manifestUnits.Count -gt 0 -and -not $manifestIds.ContainsKey($b.Unit)) {
        $malformed += "$($b.Unit) | $($b.File) | unit id not in items/manifest.md"
    }
    if ($seen.ContainsKey($b.Unit)) {
        $malformed += "$($b.Unit) | $($b.File) | id appears again (first in $($seen[$b.Unit]))"
    } else {
        $seen[$b.Unit] = $b.File
    }
}
foreach ($u in $manifestUnits) {
    if (-not $seen.ContainsKey($u.Id)) { $malformed += "$($u.Id) | (no result file) | manifest unit with no block" }
}

# --- the tally text ---
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# tally.md - generated by ../tally.ps1 -Flag $($Flag -join ',') on $(Get-Date -Format 'yyyy-MM-dd')")
$lines.Add('')
$lines.Add("Blocks: $($blocks.Count) in $($files.Count) result files")
$lines.Add('')
$lines.Add('Relation counts:')
foreach ($g in ($blocks | Group-Object { $_.Relation } | Sort-Object Count -Descending)) {
    $lines.Add(("{0,5}  {1}" -f $g.Count, $g.Name))
}
$lines.Add('')
$lines.Add("Flagged ($($Flag -join ', ')):")
foreach ($b in $blocks | Where-Object { $Flag -contains $_.Relation }) {
    $lines.Add(("{0} | {1} | {2}" -f $b.Unit, $b.Relation, $b.Section))
    $lines.Add("   quote: $($b.Quote)")
    $lines.Add("   note:  $($b.Note)")
}
$lines.Add('')
$lines.Add('By section (document order):')
if ($manifestUnits.Count -eq 0) {
    $lines.Add("   no items/manifest.md under $runPath - section table and unit checks skipped")
} else {
    $sections = @()
    foreach ($u in $manifestUnits) {
        if ($sections.Count -gt 0 -and $sections[-1].Section -eq $u.Section) { $sections[-1].Units += $u.Id }
        else { $sections += [pscustomobject]@{ Section = $u.Section; Units = @($u.Id) } }
    }
    $lines.Add("| section | first unit | units | $($labels -join ' | ') |")
    $lines.Add("|---|---|---|$(($labels | ForEach-Object { '---' }) -join '|')|")
    foreach ($s in $sections) {
        $mine = $blocks | Where-Object { $s.Units -contains $_.Unit }
        $cells = foreach ($l in $labels) { @($mine | Where-Object { $_.Relation -eq $l }).Count }
        $lines.Add("| $($s.Section -replace '\|', '\|') | $($s.Units[0]) | $($s.Units.Count) | $($cells -join ' | ') |")
    }
}
$lines.Add('')
$lines.Add("Malformed: $($malformed.Count)")
foreach ($m in $malformed) { $lines.Add("   $m") }

$text = ($lines -join "`n") + "`n"
[IO.File]::WriteAllText($Out, $text, (New-Object System.Text.UTF8Encoding($false)))
Write-Output $text.TrimEnd("`n")
Write-Output ''
Write-Output "-> $Out"
if ($malformed.Count -gt 0) { exit 1 }
exit 0
