# Self-test for tally.ps1: a temp run folder with a five-unit manifest and two result files
# carrying one of each defect the Malformed section must flag, then a clean run. Plain
# assertions, no Pester. Run from this folder: .\tally.test.ps1 (exit 0 = pass).
# ASCII only: Windows PowerShell 5.1 reads an unmarked file as ANSI.
$ErrorActionPreference = 'Stop'
$tally = Join-Path $PSScriptRoot 'tally.ps1'
$failures = @()
function Check([bool] $ok, [string] $what) { if (-not $ok) { $script:failures += $what; Write-Host "FAIL  $what" } else { Write-Host "ok    $what" } }

function New-Run([string] $name) {
    $run = Join-Path ([IO.Path]::GetTempPath()) ("sp-tally-" + $name + "-" + [Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path (Join-Path $run 'items') | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $run 'results') | Out-Null
    @(
        '# Units of doc.md', '', 'Source sha256 abc; 5 units.', '',
        '| Unit | Section | First line |', '|---|---|---|',
        '| unit-001 | (frontmatter) | --- |',
        '| unit-002 | ## Rules | The first rule |',
        '| unit-003 | ## Rules | The second rule |',
        '| unit-004 | ## Traps | A trap |',
        '| unit-005 | ## Traps | Another trap |'
    ) | Set-Content (Join-Path $run 'items\manifest.md') -Encoding UTF8
    return $run
}

function Block([string] $unit, [string] $section, [string] $relation, [string] $note) {
    return @("## $unit", "- section: $section", "- quote: q...", "- counterpart: SKILL.md > x", "- relation: $relation", "- note: $note", '')
}

function Invoke-Tally([string] $run, [string] $out) {
    & powershell -NoProfile -ExecutionPolicy Bypass -File $tally -Run $run -Out $out | Out-Null
    return $LASTEXITCODE
}

# --- one of each defect ---
$run = New-Run 'defects'
$a = @()
$a += Block 'unit-001' '(frontmatter)' 'restated' '-'
$a += Block 'unit-002' '## Rules' 'weakened' 'a label the protocol does not have'      # 1. bad relation
$a += Block 'unit-003' '## Rules' 'narrowed' ''                                         # 2. empty note off restated
$a | Set-Content (Join-Path $run 'results\arm-A-rules.md') -Encoding UTF8
$b = @()
$b += Block 'unit-004' '## Traps' 'absent' 'gone'
$b += Block 'unit-099' '## Traps' 'restated' '-'                                         # 3. not in the manifest
$b += Block 'unit-002' '## Rules' 'restated' '-'                                         # 4. duplicate id across files
# unit-005 has no block                                                                 # 5. manifest unit without a block
$b | Set-Content (Join-Path $run 'results\arm-A-traps.md') -Encoding UTF8

$out = Join-Path $run 'tally.md'
$code = Invoke-Tally $run $out
$text = [IO.File]::ReadAllText($out)
Check ($code -eq 1) 'defects: exit code 1'
Check ($text -match "Malformed: 5") 'defects: five malformed lines counted'
Check ($text -match "unit-002 \| arm-A-rules\.md \| relation 'weakened'") 'defects: bad relation flagged'
Check ($text -match "unit-003 \| arm-A-rules\.md \| empty note on relation 'narrowed'") 'defects: empty note flagged'
Check ($text -match "unit-099 \| arm-A-traps\.md \| unit id not in items/manifest\.md") 'defects: unknown unit flagged'
Check ($text -match "unit-002 \| arm-A-traps\.md \| id appears again \(first in arm-A-rules\.md\)") 'defects: duplicate id flagged'
Check ($text -match "unit-005 \| \(no result file\) \| manifest unit with no block") 'defects: missing block flagged'
Check ($text -match "\| ## Rules \| unit-002 \| 2 \|") 'defects: by-section row for Rules'
Check ($text.StartsWith('# tally.md - generated by ../tally.ps1 -Flag absent,reversed,delegated,narrowed on ')) 'defects: header line'
$bytes = [IO.File]::ReadAllBytes($out)
Check (-not ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF)) 'defects: no BOM'
Remove-Item $run -Recurse -Force

# --- clean ---
$run = New-Run 'clean'
$a = @()
$a += Block 'unit-001' '(frontmatter)' 'restated' '-'
$a += Block 'unit-002' '## Rules' 'narrowed' 'B drops the second clause'
$a += Block 'unit-003' '## Rules' 'restated' '-'
$a | Set-Content (Join-Path $run 'results\arm-A-rules.md') -Encoding UTF8
$b = @()
$b += Block 'unit-004' '## Traps' 'absent' 'gone'
$b += Block 'unit-005' '## Traps' 'broadened' 'B applies it to every run'
$b | Set-Content (Join-Path $run 'results\arm-A-traps.md') -Encoding UTF8

$out = Join-Path $run 'tally.md'
$code = Invoke-Tally $run $out
$text = [IO.File]::ReadAllText($out)
Check ($code -eq 0) 'clean: exit code 0'
Check ($text -match "Malformed: 0") 'clean: no malformed lines'
Check ($text -match "Blocks: 5 in 2 result files") 'clean: block count'
Check ($text -match "unit-002 \| narrowed \| ## Rules") 'clean: narrowed is flagged by default'
Check (-not ($text -match "unit-005 \| broadened")) 'clean: broadened is not flagged'
Check ($text -match "\| ## Traps \| unit-004 \| 2 \| 0 \| 0 \| 1 \| 0 \| 0 \| 1 \| 0 \|") 'clean: by-section counts in label order'
Remove-Item $run -Recurse -Force

if ($failures.Count -gt 0) { Write-Host "$($failures.Count) failure(s)"; exit 1 }
Write-Host 'tally.test.ps1: all checks passed'
exit 0
